namespace GHB.DP2.SourceGenerators.Templates;

public static class ActivityInfoTemplate
{
    private const string Template =
        """
        // <auto-generated />
        using System.Collections.Generic;
        using LanguageExt;
        using static LanguageExt.Prelude;
        using GHB.DP2.Domain.Common;

        {NAMESPACE_START}
        {INDENT}partial class {CLASS_NAME}
        {INDENT}{
        {INDENT}    private readonly List<ActivityInfo> _activities = new();

        {INDENT}    /// <summary>
        {INDENT}    /// Gets the collection of activity information records associated with this entity.
        {INDENT}    /// </summary>
        {INDENT}    public virtual IReadOnlyCollection<ActivityInfo> Activities => _activities.AsReadOnly();

        {INDENT}    /// <summary>
        {INDENT}    /// Adds an activity information record to this entity's activity collection.
        {INDENT}    /// </summary>
        {INDENT}    /// <param name="activityInfo">The activity information to add.</param>
        {INDENT}    /// <returns>A unit value indicating the operation completed.</returns>
        {INDENT}    public Unit AddActivity(ActivityInfo activityInfo)
        {INDENT}    {
        {INDENT}        _activities.Add(activityInfo);
        {INDENT}        return unit;
        {INDENT}    }
        
        {INDENT}    Unit IHasActivityInfo.ClearActivity()
        {INDENT}    {
        {INDENT}        _activities.Clear();
        {INDENT}        return unit;
        {INDENT}    }   
        {INDENT}}
        {NAMESPACE_END}
        """;

    public static string Generate(string? namespaceName, string className)
    {
        var indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";

        var result =
            Template.Replace("{CLASS_NAME}", className)
                    .Replace("{INDENT}", indent)
                    .Replace("{NAMESPACE_START}",
                        string.IsNullOrEmpty(namespaceName) ? "" : $"namespace {namespaceName}\n{{")
                    .Replace("{NAMESPACE_END}",
                        string.IsNullOrEmpty(namespaceName) ? "" : "}");

        return result;
    }
}
