// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GHB.DP2.Application.EventHandlers.SenEmail.Templateds
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PlanNotificationTemplate : PlanNotificationTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html>\n<style>\n  * {\n    box-sizing: border-box;\n    padding: 0;\n    margin: 0;\n  }\n\n  html,\n  body {\n    font-family: Arial, Helvetica, sans-serif;\n    line-height: 1.5;\n    color: #000;\n    background-color: #fff;\n    font-size: 16px;\n  }\n\n  table {\n    width: 100%;\n    border-collapse: collapse;\n  }\n</style>\n<html>\n\n<head>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  <title> Digital Procurement (DP)</title>\n</head>\n\n<body>\n  <div style=\"\n  max-width: 1200px;\n  width: 100%;\n  margin-left: auto;\n  margin-right: auto;\n  padding: 10px;\">\n    <table>\n      <tr>\n        <td colspan=\"2\">\n          <div style=\"box-shadow: rgba(0, 0, 0, 0.45) 0px 25px 20px -20px; padding: 10px;\">\n            <img src=\"https://www.ghbank.co.th/assets/about/img/logo-ghb.png\" width=\"120\"\n              style=\"display: block; margin: auto;\">\n          </div>\n        </td>\n      </tr>\n\n      <tr>\n        <td colspan=\"2\" style=\"padding-top:20px; padding-left:10px; vertical-align: top;\">\n          <p style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">เร\x0E35ยน &nbsp;&nbsp; ");
            
            #line 50 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Dear));
            
            #line default
            #line hidden
            this.Write("</p>\n        </td>\n      </tr>\n      <tr>\n        <td colspan=\"2\" style=\"padding-left:60px; padding-right:10px; padding-bottom:20px; padding-top:20px;\">\n            <p style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">");
            
            #line 55 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Description));
            
            #line default
            #line hidden
            this.Write("</p>\n        </td>\n      </tr>\n\n      <tr>\n        <td style=\"width: 200px; padding-bottom:5px; padding-top:5px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              เลขท\x0E35\x0E48รายการจ\x0E31ดซ\x0E37\x0E49อจ\x0E31ดจ\x0E49าง\n          </dd>\n        </dl>\n        </td>\n        <td style=\"padding-left:10px; padding-right:10px;\">\n          <dl>\n            <dd style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              : ");
            
            #line 71 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PlanNumber));
            
            #line default
            #line hidden
            this.Write("\n            </dd>\n          </dl>\n        </td>\n      </tr>\n\n      <tr>\n        <td style=\"width: 150px; padding-bottom:5px; padding-top:5px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              ว\x0E34ธ\x0E35การจ\x0E31ดหา\n          </dd>\n        </dl>\n        </td>\n        <td style=\"padding-left:10px; padding-right:10px;\">\n          <dl>\n            <dd style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              : ");
            
            #line 89 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.SupplyMethodValue));
            
            #line default
            #line hidden
            this.Write("\n            </dd>\n          </dl>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"width: 150px; padding-bottom:5px; padding-top:5px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              ช\x0E37\x0E48อโครงการ\n          </dd>\n        </dl>\n        </td>\n        <td style=\"padding-left:10px; padding-right:10px;\">\n          <dl>\n            <dd style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              : ");
            
            #line 106 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.PlanName));
            
            #line default
            #line hidden
            this.Write("\n            </dd>\n          </dl>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"width: 150px; padding-bottom:5px; padding-top:5px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              วงเง\x0E34น (บาท)\n          </dd>\n        </dl>\n        </td>\n        <td style=\"padding-left:10px; padding-right:10px;\">\n          <dl>\n            <dd style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n                : ");
            
            #line 123 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Budget));
            
            #line default
            #line hidden
            this.Write("\n            </dd>\n          </dl>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"width: 150px; padding-bottom:5px; padding-top:5px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              สถานะ\n          </dd>\n        </dl>\n        </td>\n        <td style=\"padding-left:10px; padding-right:10px;\">\n          <dl>\n            <dd style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n                : ");
            
            #line 140 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Status));
            
            #line default
            #line hidden
            this.Write("\n            </dd>\n          </dl>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"width: 150px; padding-bottom:5px; padding-top:5px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              ความเห\x0E47น\n          </dd>\n        </dl>\n        </td>\n        <td style=\"padding-left:10px; padding-right:10px;\">\n          <dl>\n            <dd style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n                : ");
            
            #line 157 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Remark));
            
            #line default
            #line hidden
            this.Write("\n            </dd>\n          </dl>\n        </td>\n      </tr>\n\n      <tr>\n        <td style=\"width: 200px; padding-bottom:5px; padding-top:50px;\">\n        <dl>\n          <dd\n            style=\"margin-left: 10px;font-family:Arial,Tahoma,sans-serif;font-size:16px;\">\n              <a href=\"");
            
            #line 168 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Url));
            
            #line default
            #line hidden
            this.Write("\" target=\"_blank\">");
            
            #line 168 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MessageClick));
            
            #line default
            #line hidden
            this.Write("</a>\n          </dd>\n        </dl>\n        </td>\n      </tr>\n\n      <tr>\n        <td colspan=\"2\" style=\"padding-bottom:40px; padding-top:40px; padding-left:10px; padding-right:10px;\">\n          <p style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">ขอแสดงความน\x0E31บถ\x0E37อ</p>\n          <p style=\"font-family:Arial,Tahoma,sans-serif;font-size:16px;\">ธนาคารอาคารสงเคราะห\x0E4C</p>\n        </td>\n      </tr>\n      <tr style=\"background-color: #DBDBDB;\">\n        <td colspan=\"2\" style=\"text-align: center; padding-bottom:10px; padding-top:10px;\">\n          <p style=\"font-family:Arial,Tahoma,sans-serif;font-weight: bold; font-size: 13px;\"> Government Housing Bank ©\n            2023. All Rights\n            Reserved.</p>\n        </td>\n      </tr>\n    </table>\n  </div>\n</body>\n</html>\n\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 198 "/home/tanaphone/work/GHB-DP2/DP2/Backend/GHB.DP2.Application/EventHandlers/SenEmail/Templateds/PlanNotificationTemplate.tt"

    public string Subject { get; init; }

    public string Dear { get; init; }

    public string Description { get; init; }

    public string PlanNumber { get; init; }

    public string SupplyMethodValue { get; init; }

    public string PlanName { get; init; }

    public string Budget { get; init; }

    public string Status { get; init; }

    public string Remark { get; init; }    

    public string MessageClick { get; init; }

    public string Url { get; init; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class PlanNotificationTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
