// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAttacementOnRp01Rp02 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "Rete",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenalty",
                newName: "Rate");

            migrationBuilder.CreateTable(
                name: "RpAuditAndRevenueAttachment",
                schema: "Report",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    RpAuditAndRevenueId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RpAuditAndRevenueAttachment", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RpAuditAndRevenueAttachment_RpAuditAndRevenue_RpAuditAndRev~",
                        column: x => x.RpAuditAndRevenueId,
                        principalSchema: "Report",
                        principalTable: "RpAuditAndRevenue",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_RpAuditAndRevenueAttachment_SuParameter_DocumentTypeCode",
                        column: x => x.DocumentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RpContractCompletionByQuarterAttachment",
                schema: "Report",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    RpContractCompletionByQuarterId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RpContractCompletionByQuarterAttachment", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RpContractCompletionByQuarterAttachment_RpContractCompletio~",
                        column: x => x.RpContractCompletionByQuarterId,
                        principalSchema: "Report",
                        principalTable: "RpContractCompletionByQuarter",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_RpContractCompletionByQuarterAttachment_SuParameter_Documen~",
                        column: x => x.DocumentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RpAuditAndRevenueAttachment_DocumentTypeCode",
                schema: "Report",
                table: "RpAuditAndRevenueAttachment",
                column: "DocumentTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_RpAuditAndRevenueAttachment_RpAuditAndRevenueId",
                schema: "Report",
                table: "RpAuditAndRevenueAttachment",
                column: "RpAuditAndRevenueId");

            migrationBuilder.CreateIndex(
                name: "IX_RpContractCompletionByQuarterAttachment_DocumentTypeCode",
                schema: "Report",
                table: "RpContractCompletionByQuarterAttachment",
                column: "DocumentTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_RpContractCompletionByQuarterAttachment_RpContractCompletio~",
                schema: "Report",
                table: "RpContractCompletionByQuarterAttachment",
                column: "RpContractCompletionByQuarterId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RpAuditAndRevenueAttachment",
                schema: "Report");

            migrationBuilder.DropTable(
                name: "RpContractCompletionByQuarterAttachment",
                schema: "Report");

            migrationBuilder.RenameColumn(
                name: "Rate",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenalty",
                newName: "Rete");
        }
    }
}
