// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddVatIcludeType : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw119VendorParcel",
                type: "character varying(50)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "VatIncludeTypeCode",
                schema: "Procurement",
                table: "P79Clause2VendorParcel",
                type: "character varying(50)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Pw119VendorParcel_VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw119VendorParcel",
                column: "VatIncludeTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_P79Clause2VendorParcel_VatIncludeTypeCode",
                schema: "Procurement",
                table: "P79Clause2VendorParcel",
                column: "VatIncludeTypeCode");

            migrationBuilder.AddForeignKey(
                name: "FK_P79Clause2VendorParcel_SuParameter_VatIncludeTypeCode",
                schema: "Procurement",
                table: "P79Clause2VendorParcel",
                column: "VatIncludeTypeCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");

            migrationBuilder.AddForeignKey(
                name: "FK_Pw119VendorParcel_SuParameter_VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw119VendorParcel",
                column: "VatIncludeTypeCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_P79Clause2VendorParcel_SuParameter_VatIncludeTypeCode",
                schema: "Procurement",
                table: "P79Clause2VendorParcel");

            migrationBuilder.DropForeignKey(
                name: "FK_Pw119VendorParcel_SuParameter_VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw119VendorParcel");

            migrationBuilder.DropIndex(
                name: "IX_Pw119VendorParcel_VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw119VendorParcel");

            migrationBuilder.DropIndex(
                name: "IX_P79Clause2VendorParcel_VatIncludeTypeCode",
                schema: "Procurement",
                table: "P79Clause2VendorParcel");

            migrationBuilder.DropColumn(
                name: "VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw119VendorParcel");

            migrationBuilder.DropColumn(
                name: "VatIncludeTypeCode",
                schema: "Procurement",
                table: "P79Clause2VendorParcel");
        }
    }
}
