// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDocumentHistoryReportAuditAndRevenue : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "RpAuditAndRevenueDocumentHistory",
                schema: "Report",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentType = table.Column<string>(type: "text", nullable: false),
                    StatusState = table.Column<string>(type: "text", nullable: false),
                    RpAuditAndRevenueId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    Version = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsReplaced = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RpAuditAndRevenueDocumentHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RpAuditAndRevenueDocumentHistory_RpAuditAndRevenue_RpAuditA~",
                        column: x => x.RpAuditAndRevenueId,
                        principalSchema: "Report",
                        principalTable: "RpAuditAndRevenue",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RpAuditAndRevenueDocumentHistory_RpAuditAndRevenueId",
                schema: "Report",
                table: "RpAuditAndRevenueDocumentHistory",
                column: "RpAuditAndRevenueId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RpAuditAndRevenueDocumentHistory",
                schema: "Report");
        }
    }
}
