// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddProcurementSuppliesDivision : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PJp005ProcurementSuppliesDivision",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    PJp005Id = table.Column<Guid>(type: "uuid", nullable: false),
                    SuUserId = table.Column<Guid>(type: "uuid", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    FullPositionName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PJp005ProcurementSuppliesDivision", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PJp005ProcurementSuppliesDivision_PJp005_PJp005Id",
                        column: x => x.PJp005Id,
                        principalSchema: "Procurement",
                        principalTable: "PJp005",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PJp005ProcurementSuppliesDivision_SuUser_SuUserId",
                        column: x => x.SuUserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PJp005ProcurementSuppliesDivision_PJp005Id",
                schema: "Procurement",
                table: "PJp005ProcurementSuppliesDivision",
                column: "PJp005Id");

            migrationBuilder.CreateIndex(
                name: "IX_PJp005ProcurementSuppliesDivision_SuUserId",
                schema: "Procurement",
                table: "PJp005ProcurementSuppliesDivision",
                column: "SuUserId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PJp005ProcurementSuppliesDivision",
                schema: "Procurement");
        }
    }
}
