// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDisbursementApprovalAttachment : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CmDisbursementApprovalAttachments",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    CmDisbursementApprovalId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CmDisbursementApprovalAttachments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CmDisbursementApprovalAttachments_CmDisbursementApproval_Cm~",
                        column: x => x.CmDisbursementApprovalId,
                        principalSchema: "ContractManagement",
                        principalTable: "CmDisbursementApproval",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_CmDisbursementApprovalAttachments_SuParameter_DocumentTypeC~",
                        column: x => x.DocumentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CmDisbursementApprovalAttachments_CmDisbursementApprovalId",
                schema: "ContractManagement",
                table: "CmDisbursementApprovalAttachments",
                column: "CmDisbursementApprovalId");

            migrationBuilder.CreateIndex(
                name: "IX_CmDisbursementApprovalAttachments_DocumentTypeCode",
                schema: "ContractManagement",
                table: "CmDisbursementApprovalAttachments",
                column: "DocumentTypeCode");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CmDisbursementApprovalAttachments",
                schema: "ContractManagement");
        }
    }
}
