// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddVendorChecker : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsContractGuarantee",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<decimal>(
                name: "PercentageContract",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "numeric",
                nullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "DeliveryPeriod",
                schema: "Procurement",
                table: "PpPurchaseRequisition",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.CreateTable(
                name: "CaContractInvitationVendorChecker",
                schema: "ContractAgreement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractInvitationVendorsId = table.Column<Guid>(type: "uuid", nullable: false),
                    CheckType = table.Column<string>(type: "text", nullable: false),
                    Result = table.Column<string>(type: "text", nullable: false),
                    ResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    Remark = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractInvitationVendorChecker", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractInvitationVendorChecker_CaContractInvitationVendo~",
                        column: x => x.ContractInvitationVendorsId,
                        principalSchema: "ContractAgreement",
                        principalTable: "CaContractInvitationVendors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractInvitationVendorShareholderChecker",
                schema: "ContractAgreement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractInvitationVendorShareholdersId = table.Column<Guid>(type: "uuid", nullable: false),
                    CheckType = table.Column<string>(type: "text", nullable: false),
                    Result = table.Column<string>(type: "text", nullable: false),
                    ResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    Remark = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractInvitationVendorShareholderChecker", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractInvitationVendorShareholderChecker_CaContractInvi~",
                        column: x => x.ContractInvitationVendorShareholdersId,
                        principalSchema: "ContractAgreement",
                        principalTable: "CaContractInvitationVendorShareholders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CaContractInvitationVendorChecker_ContractInvitationVendors~",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorChecker",
                column: "ContractInvitationVendorsId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractInvitationVendorShareholderChecker_ContractInvita~",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholderChecker",
                column: "ContractInvitationVendorShareholdersId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CaContractInvitationVendorChecker",
                schema: "ContractAgreement");

            migrationBuilder.DropTable(
                name: "CaContractInvitationVendorShareholderChecker",
                schema: "ContractAgreement");

            migrationBuilder.DropColumn(
                name: "IsContractGuarantee",
                schema: "Procurement",
                table: "PpTorDraft");

            migrationBuilder.DropColumn(
                name: "PercentageContract",
                schema: "Procurement",
                table: "PpTorDraft");

            migrationBuilder.AlterColumn<int>(
                name: "DeliveryPeriod",
                schema: "Procurement",
                table: "PpPurchaseRequisition",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);
        }
    }
}
