// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddContractCompletionQuarterDocument : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "DocumentId",
                schema: "Report",
                table: "RpContractCompletionByQuarter",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "RpContractCompletionByQuarterDocumentHistory",
                schema: "Report",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentType = table.Column<string>(type: "text", nullable: false),
                    StatusState = table.Column<string>(type: "text", nullable: false),
                    RpContractCompletionByQuarterId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    Version = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsReplaced = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RpContractCompletionByQuarterDocumentHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RpContractCompletionByQuarterDocumentHistory_RpContractComp~",
                        column: x => x.RpContractCompletionByQuarterId,
                        principalSchema: "Report",
                        principalTable: "RpContractCompletionByQuarter",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RpContractCompletionByQuarterDocumentHistory_RpContractComp~",
                schema: "Report",
                table: "RpContractCompletionByQuarterDocumentHistory",
                column: "RpContractCompletionByQuarterId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RpContractCompletionByQuarterDocumentHistory",
                schema: "Report");

            migrationBuilder.DropColumn(
                name: "DocumentId",
                schema: "Report",
                table: "RpContractCompletionByQuarter");
        }
    }
}
