// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ClearDeadlineDescriptionInMdpTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DeadlineDescription",
                schema: "Procurement",
                table: "PpMedianPrice");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "DeadlineDescription",
                schema: "Procurement",
                table: "PpMedianPrice",
                type: "text",
                nullable: false,
                defaultValue: "");
        }
    }
}
