// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAttachmentInvitationVendor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CaContractInvitationVendorAttachments",
                schema: "ContractAgreement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    Type = table.Column<string>(type: "text", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    CaContractInvitationVendorsId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractInvitationVendorAttachments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractInvitationVendorAttachments_CaContractInvitationV~",
                        column: x => x.CaContractInvitationVendorsId,
                        principalSchema: "ContractAgreement",
                        principalTable: "CaContractInvitationVendors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractInvitationVendorAttachments_SuParameter_DocumentT~",
                        column: x => x.DocumentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CaContractInvitationVendorAttachments_CaContractInvitationV~",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorAttachments",
                column: "CaContractInvitationVendorsId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractInvitationVendorAttachments_DocumentTypeCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorAttachments",
                column: "DocumentTypeCode");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CaContractInvitationVendorAttachments",
                schema: "ContractAgreement");
        }
    }
}
