// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddGuaranteeBankForeignKeyToContractDraft : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "GuaranteeBank",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "character varying(50)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftTermsConditions_GuaranteeBank",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                column: "GuaranteeBank");

            migrationBuilder.AddForeignKey(
                name: "FK_CaContractDraftTermsConditions_SuParameter_GuaranteeBank",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                column: "GuaranteeBank",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CaContractDraftTermsConditions_SuParameter_GuaranteeBank",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropIndex(
                name: "IX_CaContractDraftTermsConditions_GuaranteeBank",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.AlterColumn<string>(
                name: "GuaranteeBank",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldNullable: true);
        }
    }
}
