// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ClearRequiredFieldRpContractCompletionByQuarterTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Report",
                table: "RpContractCompletionByQuarterDetail",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(2000)",
                oldMaxLength: 2000);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Report",
                table: "RpContractCompletionByQuarterDetail",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);
        }
    }
}
