// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FixMissingMigrations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CmContractGuaranteeReturnAttachments_CmContractGuaranteeRet~",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAttachments");

            migrationBuilder.DropForeignKey(
                name: "FK_P79Clause2Attachments_P79Clause2_P79Clause2Id",
                schema: "Procurement",
                table: "P79Clause2Attachments");

            migrationBuilder.DropForeignKey(
                name: "FK_PPettyCashReimbursementAttachments_PPettyCashReimbursement_~",
                schema: "Procurement",
                table: "PPettyCashReimbursementAttachments");

            migrationBuilder.DropForeignKey(
                name: "FK_Pw119Attachments_Pw119_Pw119Id",
                schema: "Procurement",
                table: "Pw119Attachments");
            
            migrationBuilder.Sql("DELETE FROM \"Procurement\".\"Pw119Attachments\" WHERE \"Pw119Id\" IS NULL;");

            migrationBuilder.AlterColumn<Guid>(
                name: "Pw119Id",
                schema: "Procurement",
                table: "Pw119Attachments",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);
            
            migrationBuilder.Sql("DELETE FROM \"Procurement\".\"PPettyCashReimbursementAttachments\" WHERE \"PPettyCashReimbursementId\" IS NULL;");

            migrationBuilder.AlterColumn<Guid>(
                name: "PPettyCashReimbursementId",
                schema: "Procurement",
                table: "PPettyCashReimbursementAttachments",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsExpenseAttachment",
                schema: "Procurement",
                table: "PExpenseDisbursementAttachment",
                type: "boolean",
                nullable: false,
                defaultValue: false);
            
            migrationBuilder.Sql("DELETE FROM \"Procurement\".\"P79Clause2Attachments\" WHERE \"P79Clause2Id\" IS NULL;");

            migrationBuilder.AlterColumn<Guid>(
                name: "P79Clause2Id",
                schema: "Procurement",
                table: "P79Clause2Attachments",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);
            
            migrationBuilder.Sql("DELETE FROM \"ContractManagement\".\"CmContractGuaranteeReturnAttachments\" WHERE \"CmContractGuaranteeReturnId\" IS NULL;");

            migrationBuilder.AlterColumn<Guid>(
                name: "CmContractGuaranteeReturnId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAttachments",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_CmContractGuaranteeReturnAttachments_CmContractGuaranteeRet~",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAttachments",
                column: "CmContractGuaranteeReturnId",
                principalSchema: "ContractManagement",
                principalTable: "CmContractGuaranteeReturn",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_P79Clause2Attachments_P79Clause2_P79Clause2Id",
                schema: "Procurement",
                table: "P79Clause2Attachments",
                column: "P79Clause2Id",
                principalSchema: "Procurement",
                principalTable: "P79Clause2",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_PPettyCashReimbursementAttachments_PPettyCashReimbursement_~",
                schema: "Procurement",
                table: "PPettyCashReimbursementAttachments",
                column: "PPettyCashReimbursementId",
                principalSchema: "Procurement",
                principalTable: "PPettyCashReimbursement",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Pw119Attachments_Pw119_Pw119Id",
                schema: "Procurement",
                table: "Pw119Attachments",
                column: "Pw119Id",
                principalSchema: "Procurement",
                principalTable: "Pw119",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CmContractGuaranteeReturnAttachments_CmContractGuaranteeRet~",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAttachments");

            migrationBuilder.DropForeignKey(
                name: "FK_P79Clause2Attachments_P79Clause2_P79Clause2Id",
                schema: "Procurement",
                table: "P79Clause2Attachments");

            migrationBuilder.DropForeignKey(
                name: "FK_PPettyCashReimbursementAttachments_PPettyCashReimbursement_~",
                schema: "Procurement",
                table: "PPettyCashReimbursementAttachments");

            migrationBuilder.DropForeignKey(
                name: "FK_Pw119Attachments_Pw119_Pw119Id",
                schema: "Procurement",
                table: "Pw119Attachments");

            migrationBuilder.DropColumn(
                name: "IsExpenseAttachment",
                schema: "Procurement",
                table: "PExpenseDisbursementAttachment");

            migrationBuilder.AlterColumn<Guid>(
                name: "Pw119Id",
                schema: "Procurement",
                table: "Pw119Attachments",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AlterColumn<Guid>(
                name: "PPettyCashReimbursementId",
                schema: "Procurement",
                table: "PPettyCashReimbursementAttachments",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AlterColumn<Guid>(
                name: "P79Clause2Id",
                schema: "Procurement",
                table: "P79Clause2Attachments",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AlterColumn<Guid>(
                name: "CmContractGuaranteeReturnId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAttachments",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddForeignKey(
                name: "FK_CmContractGuaranteeReturnAttachments_CmContractGuaranteeRet~",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAttachments",
                column: "CmContractGuaranteeReturnId",
                principalSchema: "ContractManagement",
                principalTable: "CmContractGuaranteeReturn",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_P79Clause2Attachments_P79Clause2_P79Clause2Id",
                schema: "Procurement",
                table: "P79Clause2Attachments",
                column: "P79Clause2Id",
                principalSchema: "Procurement",
                principalTable: "P79Clause2",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_PPettyCashReimbursementAttachments_PPettyCashReimbursement_~",
                schema: "Procurement",
                table: "PPettyCashReimbursementAttachments",
                column: "PPettyCashReimbursementId",
                principalSchema: "Procurement",
                principalTable: "PPettyCashReimbursement",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Pw119Attachments_Pw119_Pw119Id",
                schema: "Procurement",
                table: "Pw119Attachments",
                column: "Pw119Id",
                principalSchema: "Procurement",
                principalTable: "Pw119",
                principalColumn: "Id");
        }
    }
}
