// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTableCamContractAmendmentExtendChange : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CamContractAmendmentExtendChange",
                schema: "ContractAmendment",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CamContractAmendmentId = table.Column<Guid>(type: "uuid", nullable: false),
                    ChangeType = table.Column<string>(type: "text", nullable: false),
                    PaymentTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    WorkStartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    NewEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    Status = table.Column<string>(type: "text", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CamContractAmendmentExtendChange", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChange_CamContractAmendment_CamCo~",
                        column: x => x.CamContractAmendmentId,
                        principalSchema: "ContractAmendment",
                        principalTable: "CamContractAmendment",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChange_SuParameter_PaymentTypeCode",
                        column: x => x.PaymentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CamContractAmendmentExtendChangeAcceptor",
                schema: "ContractAmendment",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    IsUnableToPerformDuties = table.Column<bool>(type: "boolean", nullable: false),
                    CommitteePositionsCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    CamContractAmendmentExtendChangeId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true),
                    Type = table.Column<string>(type: "text", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    EmployeeCode = table.Column<string>(type: "text", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    BusinessUnitName = table.Column<string>(type: "text", nullable: false),
                    PositionName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    DelegateeId = table.Column<Guid>(type: "uuid", nullable: true),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ActionAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    IsCurrent = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CamContractAmendmentExtendChangeAcceptor", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeAcceptor_CamContractAmendme~",
                        column: x => x.CamContractAmendmentExtendChangeId,
                        principalSchema: "ContractAmendment",
                        principalTable: "CamContractAmendmentExtendChange",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeAcceptor_SuDelegatee_Delega~",
                        column: x => x.DelegateeId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuDelegatee",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeAcceptor_SuParameter_Commit~",
                        column: x => x.CommitteePositionsCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeAcceptor_SuUser_UserId",
                        column: x => x.UserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                schema: "ContractAmendment",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CamContractAmendmentExtendChangeId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true),
                    Group = table.Column<string>(type: "text", nullable: false),
                    Type = table.Column<string>(type: "text", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    EmployeeCode = table.Column<string>(type: "text", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    PositionName = table.Column<string>(type: "text", nullable: false),
                    BusinessUnitName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    DelegateeId = table.Column<Guid>(type: "uuid", nullable: true),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ActionAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Remark = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CamContractAmendmentExtendChangeAssigneeConfiguration", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_CamCo~",
                        column: x => x.CamContractAmendmentExtendChangeId,
                        principalSchema: "ContractAmendment",
                        principalTable: "CamContractAmendmentExtendChange",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUse~",
                        column: x => x.UserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CamContractAmendmentExtendChangeDocumentHistory",
                schema: "ContractAmendment",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentType = table.Column<string>(type: "text", nullable: false),
                    StatusState = table.Column<string>(type: "text", nullable: false),
                    CamContractAmendmentExtendChangeId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    Version = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsReplaced = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CamContractAmendmentExtendChangeDocumentHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangeDocumentHistory_CamContract~",
                        column: x => x.CamContractAmendmentExtendChangeId,
                        principalSchema: "ContractAmendment",
                        principalTable: "CamContractAmendmentExtendChange",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CamContractAmendmentExtendChangePaymentTerm",
                schema: "ContractAmendment",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    LeadTime = table.Column<int>(type: "integer", nullable: false),
                    DeliveryDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    InstallmentPercent = table.Column<decimal>(type: "numeric", nullable: false),
                    Amount = table.Column<decimal>(type: "numeric", nullable: false),
                    AdvanceDeductionAmount = table.Column<decimal>(type: "numeric", nullable: false),
                    PerformanceDeductionAmount = table.Column<decimal>(type: "numeric", nullable: false),
                    Description = table.Column<string>(type: "text", nullable: false),
                    IsDelivery = table.Column<bool>(type: "boolean", nullable: false),
                    CamContractAmendmentExtendChangeId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CamContractAmendmentExtendChangePaymentTerm", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CamContractAmendmentExtendChangePaymentTerm_CamContractAmen~",
                        column: x => x.CamContractAmendmentExtendChangeId,
                        principalSchema: "ContractAmendment",
                        principalTable: "CamContractAmendmentExtendChange",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChange_CamContractAmendmentId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChange",
                column: "CamContractAmendmentId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChange_PaymentTypeCode",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChange",
                column: "PaymentTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAcceptor_CamContractAmendme~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAcceptor",
                column: "CamContractAmendmentExtendChangeId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAcceptor_CommitteePositions~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAcceptor",
                column: "CommitteePositionsCode");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAcceptor_DelegateeId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAcceptor",
                column: "DelegateeId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAcceptor_UserId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAcceptor",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAssigneeConfiguration_CamCo~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                column: "CamContractAmendmentExtendChangeId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAssigneeConfiguration_UserId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeDocumentHistory_CamContract~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeDocumentHistory",
                column: "CamContractAmendmentExtendChangeId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangePaymentTerm_CamContractAmen~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangePaymentTerm",
                column: "CamContractAmendmentExtendChangeId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CamContractAmendmentExtendChangeAcceptor",
                schema: "ContractAmendment");

            migrationBuilder.DropTable(
                name: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                schema: "ContractAmendment");

            migrationBuilder.DropTable(
                name: "CamContractAmendmentExtendChangeDocumentHistory",
                schema: "ContractAmendment");

            migrationBuilder.DropTable(
                name: "CamContractAmendmentExtendChangePaymentTerm",
                schema: "ContractAmendment");

            migrationBuilder.DropTable(
                name: "CamContractAmendmentExtendChange",
                schema: "ContractAmendment");
        }
    }
}
