// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSubTemplateField : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "SubTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "character varying(50)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SubTemplateText",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendor_SubTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                column: "SubTemplateCode");

            migrationBuilder.AddForeignKey(
                name: "FK_CaContractDraftVendor_SuParameter_SubTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                column: "SubTemplateCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CaContractDraftVendor_SuParameter_SubTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropIndex(
                name: "IX_CaContractDraftVendor_SubTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "SubTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "SubTemplateText",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");
        }
    }
}
