// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddAssignSegmentCodeW119And79Clause2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "AssignSegmentCode",
                schema: "Procurement",
                table: "Pw119",
                type: "character varying(50)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AssignSegmentCode",
                schema: "Procurement",
                table: "P79Clause2",
                type: "character varying(50)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Pw119_AssignSegmentCode",
                schema: "Procurement",
                table: "Pw119",
                column: "AssignSegmentCode");

            migrationBuilder.CreateIndex(
                name: "IX_P79Clause2_AssignSegmentCode",
                schema: "Procurement",
                table: "P79Clause2",
                column: "AssignSegmentCode");

            migrationBuilder.AddForeignKey(
                name: "FK_P79Clause2_SuParameter_AssignSegmentCode",
                schema: "Procurement",
                table: "P79Clause2",
                column: "AssignSegmentCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");

            migrationBuilder.AddForeignKey(
                name: "FK_Pw119_SuParameter_AssignSegmentCode",
                schema: "Procurement",
                table: "Pw119",
                column: "AssignSegmentCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_P79Clause2_SuParameter_AssignSegmentCode",
                schema: "Procurement",
                table: "P79Clause2");

            migrationBuilder.DropForeignKey(
                name: "FK_Pw119_SuParameter_AssignSegmentCode",
                schema: "Procurement",
                table: "Pw119");

            migrationBuilder.DropIndex(
                name: "IX_Pw119_AssignSegmentCode",
                schema: "Procurement",
                table: "Pw119");

            migrationBuilder.DropIndex(
                name: "IX_P79Clause2_AssignSegmentCode",
                schema: "Procurement",
                table: "P79Clause2");

            migrationBuilder.DropColumn(
                name: "AssignSegmentCode",
                schema: "Procurement",
                table: "Pw119");

            migrationBuilder.DropColumn(
                name: "AssignSegmentCode",
                schema: "Procurement",
                table: "P79Clause2");
        }
    }
}
