// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTablePpTorTemplateComputer : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PpTorTemplateComputer",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    PpTorDraftId = table.Column<Guid>(type: "uuid", nullable: false),
                    EvidenceDescription = table.Column<string>(type: "text", nullable: true),
                    EvidenceNumber = table.Column<string>(type: "text", nullable: true),
                    DocumentDescription = table.Column<string>(type: "text", nullable: true),
                    CriteriaConsiderDescription = table.Column<string>(type: "text", nullable: true),
                    ManuelDescription = table.Column<string>(type: "text", nullable: true),
                    Evidence_PresentTotal = table.Column<int>(type: "integer", nullable: true),
                    Evidence_PresentCount = table.Column<int>(type: "integer", nullable: true),
                    Evidence_PresentCountUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    Evidence_PresentCountType = table.Column<Guid>(type: "uuid", nullable: true),
                    Collateral_Amount = table.Column<decimal>(type: "numeric", nullable: true),
                    Collateral_StartDueDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Collateral_EndDueDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    PreventiveMaintenance_PmProductName = table.Column<string>(type: "text", nullable: true),
                    PreventiveMaintenance_PmCount = table.Column<int>(type: "integer", nullable: true),
                    PreventiveMaintenance_PmUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    PreventiveMaintenance_PmFinePct = table.Column<decimal>(type: "numeric", nullable: true),
                    PreventiveMaintenance_PmFineAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    PreventiveMaintenance_Condition = table.Column<string>(type: "text", nullable: true),
                    PreventiveMaintenance_DisruptedCount = table.Column<int>(type: "integer", nullable: true),
                    PreventiveMaintenance_DisruptedCountUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    PreventiveMaintenance_DisruptedPercent = table.Column<decimal>(type: "numeric", nullable: true),
                    PreventiveMaintenance_DisruptedFinePercent = table.Column<decimal>(type: "numeric", nullable: true),
                    PreventiveMaintenance_DisruptedFineAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    PreventiveMaintenance_PmFinePctUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    CorrectiveMaintenance_CmProductName = table.Column<string>(type: "text", nullable: true),
                    CorrectiveMaintenance_StartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    CorrectiveMaintenance_EndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    CorrectiveMaintenance_CmCount = table.Column<int>(type: "integer", nullable: true),
                    CorrectiveMaintenance_CmUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    CorrectiveMaintenance_CmCompleteCount = table.Column<int>(type: "integer", nullable: true),
                    CorrectiveMaintenance_CmCompleteUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    CorrectiveMaintenance_CmFinePercent = table.Column<decimal>(type: "numeric", nullable: true),
                    CorrectiveMaintenance_CmDisruptedFinePercent = table.Column<decimal>(type: "numeric", nullable: true),
                    CorrectiveMaintenance_DayStart = table.Column<Guid>(type: "uuid", nullable: true),
                    CorrectiveMaintenance_DayEnd = table.Column<Guid>(type: "uuid", nullable: true),
                    CorrectiveMaintenance_StartTime = table.Column<string>(type: "text", nullable: true),
                    CorrectiveMaintenance_EndTime = table.Column<string>(type: "text", nullable: true),
                    CorrectiveMaintenance_CmFinePercentUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    Training_TrainingCount = table.Column<int>(type: "integer", nullable: true),
                    Training_TrainingCountUnit = table.Column<Guid>(type: "uuid", nullable: true),
                    Training_TrainingUnitId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PpTorTemplateComputer", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PpTorTemplateComputer_PpTorDraft_PpTorDraftId",
                        column: x => x.PpTorDraftId,
                        principalSchema: "Procurement",
                        principalTable: "PpTorDraft",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PpTorTemplateComputer_PpTorDraftId",
                schema: "Procurement",
                table: "PpTorTemplateComputer",
                column: "PpTorDraftId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PpTorTemplateComputer",
                schema: "Procurement");
        }
    }
}
