// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTableRawErmEmployee : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateOnly>(
                name: "BirthDate",
                schema: "Raws",
                table: "RawEmployee",
                type: "date",
                nullable: true,
                oldClrType: typeof(DateOnly),
                oldType: "date");

            migrationBuilder.CreateTable(
                name: "RawErmEmployee",
                schema: "Raws",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false),
                    title = table.Column<string>(type: "text", nullable: false),
                    emp_code = table.Column<string>(type: "text", nullable: false),
                    fname_t = table.Column<string>(type: "text", nullable: false),
                    lname_t = table.Column<string>(type: "text", nullable: false),
                    idcard = table.Column<string>(type: "text", nullable: false),
                    birthdate = table.Column<string>(type: "text", nullable: true),
                    grade = table.Column<string>(type: "text", nullable: false),
                    emp_type = table.Column<string>(type: "text", nullable: false),
                    position_id = table.Column<string>(type: "text", nullable: false),
                    position_name = table.Column<string>(type: "text", nullable: false),
                    acting_position = table.Column<string>(type: "text", nullable: false),
                    manager_emp_id = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false),
                    orglevel = table.Column<string>(type: "text", nullable: false),
                    objid1 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid1 = table.Column<string>(type: "text", nullable: true),
                    short1 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name1 = table.Column<string>(type: "text", nullable: true),
                    objid2 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid2 = table.Column<string>(type: "text", nullable: true),
                    short2 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name2 = table.Column<string>(type: "text", nullable: true),
                    objid3 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid3 = table.Column<string>(type: "text", nullable: true),
                    short3 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name3 = table.Column<string>(type: "text", nullable: true),
                    objid4 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid4 = table.Column<string>(type: "text", nullable: true),
                    short4 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name4 = table.Column<string>(type: "text", nullable: true),
                    objid5 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid5 = table.Column<string>(type: "text", nullable: true),
                    short5 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name5 = table.Column<string>(type: "text", nullable: true),
                    objid6 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid6 = table.Column<string>(type: "text", nullable: true),
                    short6 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name6 = table.Column<string>(type: "text", nullable: true),
                    objid7 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid7 = table.Column<string>(type: "text", nullable: true),
                    short7 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name7 = table.Column<string>(type: "text", nullable: true),
                    objid8 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid8 = table.Column<string>(type: "text", nullable: true),
                    short8 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name8 = table.Column<string>(type: "text", nullable: true),
                    objid9 = table.Column<string>(type: "text", nullable: true),
                    org_unit_solid9 = table.Column<string>(type: "text", nullable: true),
                    short9 = table.Column<string>(type: "text", nullable: true),
                    org_unit_name9 = table.Column<string>(type: "text", nullable: true),
                    start_date = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    stop_date = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    last_action = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    data_date = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RawErmEmployee", x => x.id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RawErmEmployee",
                schema: "Raws");

            migrationBuilder.AlterColumn<DateOnly>(
                name: "BirthDate",
                schema: "Raws",
                table: "RawEmployee",
                type: "date",
                nullable: false,
                defaultValue: new DateOnly(1, 1, 1),
                oldClrType: typeof(DateOnly),
                oldType: "date",
                oldNullable: true);
        }
    }
}
