// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AlterAddIsMigrationColumn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PPurchaseOrder",
                type: "boolean",
                nullable: true,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "boolean",
                nullable: true,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpPurchaseRequisition",
                type: "boolean",
                nullable: true,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpMedianPrice",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpAppoint",
                type: "boolean",
                nullable: true,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PJp005",
                type: "boolean",
                nullable: true,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsMigration",
                schema: "Procurement",
                table: "PInvite",
                type: "boolean",
                nullable: true,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PPurchaseOrder");

            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpTorDraft");

            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpPurchaseRequisition");

            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpMedianPrice");

            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PpAppoint");

            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PJp005");

            migrationBuilder.DropColumn(
                name: "IsMigration",
                schema: "Procurement",
                table: "PInvite");
        }
    }
}
