// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ClearRequiredConditionCodeInTorDraftFineRate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_ConditionCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate");

            migrationBuilder.AlterColumn<string>(
                name: "ConditionCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "character varying(50)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(50)");

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_ConditionCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                column: "ConditionCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_ConditionCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate");

            migrationBuilder.AlterColumn<string>(
                name: "ConditionCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "character varying(50)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_ConditionCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                column: "ConditionCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
