// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddNewTablePW184 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Pw184",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Pw184Number = table.Column<string>(type: "text", nullable: false),
                    Pw184Date = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    DepartmentId = table.Column<string>(type: "text", nullable: false),
                    BudgetYear = table.Column<int>(type: "integer", nullable: false),
                    SupplyMethodCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    SupplyMethodSpecialTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    Subject = table.Column<string>(type: "text", nullable: false),
                    Source = table.Column<string>(type: "text", nullable: false),
                    Reason = table.Column<string>(type: "text", nullable: true),
                    Budget = table.Column<decimal>(type: "numeric", nullable: false),
                    IsAdvance = table.Column<bool>(type: "boolean", nullable: false),
                    AdvanceName = table.Column<string>(type: "text", nullable: true),
                    AdvancePaymentMethodCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    AdvancePaymentDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    AdvanceBankCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    AdvanceBankAccount = table.Column<string>(type: "text", nullable: true),
                    AdvanceBankBranch = table.Column<string>(type: "text", nullable: true),
                    AdvanceBankAccountName = table.Column<string>(type: "text", nullable: true),
                    AdvanceDetail = table.Column<string>(type: "text", nullable: true),
                    Status = table.Column<string>(type: "text", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    CurrentCommitteeSequence = table.Column<int>(type: "integer", nullable: false),
                    DisbursementDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    DisbursementAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    DisbursementDescription = table.Column<string>(type: "text", nullable: true),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184_RawBusinessUnit_DepartmentId",
                        column: x => x.DepartmentId,
                        principalSchema: "Raws",
                        principalTable: "RawBusinessUnit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Pw184_SuParameter_AdvanceBankCode",
                        column: x => x.AdvanceBankCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                    table.ForeignKey(
                        name: "FK_Pw184_SuParameter_AdvancePaymentMethodCode",
                        column: x => x.AdvancePaymentMethodCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                    table.ForeignKey(
                        name: "FK_Pw184_SuParameter_SupplyMethodCode",
                        column: x => x.SupplyMethodCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184_SuParameter_SupplyMethodSpecialTypeCode",
                        column: x => x.SupplyMethodSpecialTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                });

            migrationBuilder.CreateTable(
                name: "Pw184Acceptor",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Pw184Id = table.Column<Guid>(type: "uuid", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true),
                    Type = table.Column<string>(type: "text", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    EmployeeCode = table.Column<string>(type: "text", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    BusinessUnitName = table.Column<string>(type: "text", nullable: false),
                    PositionName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    DelegateeId = table.Column<Guid>(type: "uuid", nullable: true),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ActionAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    IsCurrent = table.Column<bool>(type: "boolean", nullable: false),
                    SendToAcceptorId = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184Acceptor", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184Acceptor_Pw184_Pw184Id",
                        column: x => x.Pw184Id,
                        principalSchema: "Procurement",
                        principalTable: "Pw184",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184Acceptor_SuDelegatee_DelegateeId",
                        column: x => x.DelegateeId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuDelegatee",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Pw184Acceptor_SuUser_SendToAcceptorId",
                        column: x => x.SendToAcceptorId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Pw184Acceptor_SuUser_UserId",
                        column: x => x.UserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Pw184Attachments",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    Pw184Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184Attachments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184Attachments_Pw184_Pw184Id",
                        column: x => x.Pw184Id,
                        principalSchema: "Procurement",
                        principalTable: "Pw184",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184Attachments_SuParameter_DocumentTypeCode",
                        column: x => x.DocumentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Pw184Committee",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Pw184Id = table.Column<Guid>(type: "uuid", nullable: false),
                    GroupType = table.Column<string>(type: "text", nullable: false),
                    SuUserId = table.Column<Guid>(type: "uuid", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    FullPositionName = table.Column<string>(type: "text", nullable: false),
                    CommitteePositionsCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    CommitteePositionsName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184Committee", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184Committee_Pw184_Pw184Id",
                        column: x => x.Pw184Id,
                        principalSchema: "Procurement",
                        principalTable: "Pw184",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184Committee_SuParameter_CommitteePositionsCode",
                        column: x => x.CommitteePositionsCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184Committee_SuUser_SuUserId",
                        column: x => x.SuUserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Pw184GLAccount",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Pw184Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    SoId = table.Column<string>(type: "text", nullable: false),
                    BudgetTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    GLAccountCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    ProjectNumber = table.Column<string>(type: "text", nullable: true),
                    Amount = table.Column<decimal>(type: "numeric", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184GLAccount", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184GLAccount_Pw184_Pw184Id",
                        column: x => x.Pw184Id,
                        principalSchema: "Procurement",
                        principalTable: "Pw184",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184GLAccount_SuParameter_BudgetTypeCode",
                        column: x => x.BudgetTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184GLAccount_SuParameter_GLAccountCode",
                        column: x => x.GLAccountCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Pw184Vendor",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Pw184Id = table.Column<Guid>(type: "uuid", nullable: false),
                    VendorType = table.Column<string>(type: "text", nullable: false),
                    SuVendorId = table.Column<Guid>(type: "uuid", nullable: true),
                    VendorName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    TaxNumber = table.Column<string>(type: "text", nullable: true),
                    VendorBranchNumber = table.Column<string>(type: "text", nullable: true),
                    VatIncludeTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    BillTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    BillBookNo = table.Column<string>(type: "text", nullable: true),
                    BillTypeOther = table.Column<string>(type: "text", nullable: true),
                    BillDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    BillDetail = table.Column<string>(type: "text", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184Vendor", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184Vendor_Pw184_Pw184Id",
                        column: x => x.Pw184Id,
                        principalSchema: "Procurement",
                        principalTable: "Pw184",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184Vendor_SuParameter_BillTypeCode",
                        column: x => x.BillTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184Vendor_SuParameter_VatIncludeTypeCode",
                        column: x => x.VatIncludeTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                });

            migrationBuilder.CreateTable(
                name: "Pw184VendorParcel",
                schema: "Procurement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Pw184VendorId = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    Item = table.Column<string>(type: "text", nullable: false),
                    ItemDetail = table.Column<string>(type: "text", nullable: true),
                    Quantity = table.Column<int>(type: "integer", nullable: false),
                    UnitCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    UnitPrice = table.Column<decimal>(type: "numeric", nullable: false),
                    TotalPrice = table.Column<decimal>(type: "numeric", nullable: false),
                    TotalPriceVat = table.Column<decimal>(type: "numeric", nullable: false),
                    VatIncludeTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Pw184VendorParcel", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Pw184VendorParcel_Pw184Vendor_Pw184VendorId",
                        column: x => x.Pw184VendorId,
                        principalSchema: "Procurement",
                        principalTable: "Pw184Vendor",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184VendorParcel_SuParameter_UnitCode",
                        column: x => x.UnitCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Pw184VendorParcel_SuParameter_VatIncludeTypeCode",
                        column: x => x.VatIncludeTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Pw184_AdvanceBankCode",
                schema: "Procurement",
                table: "Pw184",
                column: "AdvanceBankCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184_AdvancePaymentMethodCode",
                schema: "Procurement",
                table: "Pw184",
                column: "AdvancePaymentMethodCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184_DepartmentId",
                schema: "Procurement",
                table: "Pw184",
                column: "DepartmentId");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184_SupplyMethodCode",
                schema: "Procurement",
                table: "Pw184",
                column: "SupplyMethodCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184_SupplyMethodSpecialTypeCode",
                schema: "Procurement",
                table: "Pw184",
                column: "SupplyMethodSpecialTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Acceptor_DelegateeId",
                schema: "Procurement",
                table: "Pw184Acceptor",
                column: "DelegateeId");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Acceptor_Pw184Id",
                schema: "Procurement",
                table: "Pw184Acceptor",
                column: "Pw184Id");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Acceptor_SendToAcceptorId",
                schema: "Procurement",
                table: "Pw184Acceptor",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Acceptor_UserId",
                schema: "Procurement",
                table: "Pw184Acceptor",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Attachments_DocumentTypeCode",
                schema: "Procurement",
                table: "Pw184Attachments",
                column: "DocumentTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Attachments_Pw184Id",
                schema: "Procurement",
                table: "Pw184Attachments",
                column: "Pw184Id");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Committee_CommitteePositionsCode",
                schema: "Procurement",
                table: "Pw184Committee",
                column: "CommitteePositionsCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Committee_Pw184Id",
                schema: "Procurement",
                table: "Pw184Committee",
                column: "Pw184Id");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Committee_SuUserId",
                schema: "Procurement",
                table: "Pw184Committee",
                column: "SuUserId");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184GLAccount_BudgetTypeCode",
                schema: "Procurement",
                table: "Pw184GLAccount",
                column: "BudgetTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184GLAccount_GLAccountCode",
                schema: "Procurement",
                table: "Pw184GLAccount",
                column: "GLAccountCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184GLAccount_Pw184Id",
                schema: "Procurement",
                table: "Pw184GLAccount",
                column: "Pw184Id");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Vendor_BillTypeCode",
                schema: "Procurement",
                table: "Pw184Vendor",
                column: "BillTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Vendor_Pw184Id",
                schema: "Procurement",
                table: "Pw184Vendor",
                column: "Pw184Id");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184Vendor_VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw184Vendor",
                column: "VatIncludeTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184VendorParcel_Pw184VendorId",
                schema: "Procurement",
                table: "Pw184VendorParcel",
                column: "Pw184VendorId");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184VendorParcel_UnitCode",
                schema: "Procurement",
                table: "Pw184VendorParcel",
                column: "UnitCode");

            migrationBuilder.CreateIndex(
                name: "IX_Pw184VendorParcel_VatIncludeTypeCode",
                schema: "Procurement",
                table: "Pw184VendorParcel",
                column: "VatIncludeTypeCode");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Pw184Acceptor",
                schema: "Procurement");

            migrationBuilder.DropTable(
                name: "Pw184Attachments",
                schema: "Procurement");

            migrationBuilder.DropTable(
                name: "Pw184Committee",
                schema: "Procurement");

            migrationBuilder.DropTable(
                name: "Pw184GLAccount",
                schema: "Procurement");

            migrationBuilder.DropTable(
                name: "Pw184VendorParcel",
                schema: "Procurement");

            migrationBuilder.DropTable(
                name: "Pw184Vendor",
                schema: "Procurement");

            migrationBuilder.DropTable(
                name: "Pw184",
                schema: "Procurement");
        }
    }
}
