// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddIsPenalty : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "PenaltyIsPenalty",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "boolean",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<bool>(
                name: "PenaltyIsPenalty",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PenaltyIsPenalty",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "PenaltyIsPenalty",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions");
        }
    }
}
