// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSuSecretaryTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "SuSecretaryOwner",
                schema: "SystemUtility",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    SuUserId = table.Column<Guid>(type: "uuid", nullable: false),
                    UserFullName = table.Column<string>(type: "text", nullable: true),
                    EmployeeCode = table.Column<string>(type: "text", nullable: true),
                    PositionId = table.Column<string>(type: "text", nullable: true),
                    FullPositionName = table.Column<string>(type: "text", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SuSecretaryOwner", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SuSecretaryOwner_SuUser_SuUserId",
                        column: x => x.SuUserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SuSecretary",
                schema: "SystemUtility",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    SecretaryOwnerId = table.Column<Guid>(type: "uuid", nullable: false),
                    SuUserId = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    UserFullName = table.Column<string>(type: "text", nullable: true),
                    EmployeeCode = table.Column<string>(type: "text", nullable: true),
                    PositionId = table.Column<string>(type: "text", nullable: true),
                    FullPositionName = table.Column<string>(type: "text", nullable: true),
                    Active = table.Column<bool>(type: "boolean", nullable: true),
                    EffectiveStartDate = table.Column<DateOnly>(type: "date", nullable: true),
                    EffectiveEndDate = table.Column<DateOnly>(type: "date", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SuSecretary", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SuSecretary_SuSecretaryOwner_SecretaryOwnerId",
                        column: x => x.SecretaryOwnerId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuSecretaryOwner",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_SuSecretary_SuUser_SuUserId",
                        column: x => x.SuUserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SuSecretaryAttachment",
                schema: "SystemUtility",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    SecretaryOwnerId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "text", nullable: true),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SuSecretaryAttachment", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SuSecretaryAttachment_SuSecretaryOwner_SecretaryOwnerId",
                        column: x => x.SecretaryOwnerId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuSecretaryOwner",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_SuSecretary_SecretaryOwnerId",
                schema: "SystemUtility",
                table: "SuSecretary",
                column: "SecretaryOwnerId");

            migrationBuilder.CreateIndex(
                name: "IX_SuSecretary_SuUserId",
                schema: "SystemUtility",
                table: "SuSecretary",
                column: "SuUserId");

            migrationBuilder.CreateIndex(
                name: "IX_SuSecretaryAttachment_SecretaryOwnerId",
                schema: "SystemUtility",
                table: "SuSecretaryAttachment",
                column: "SecretaryOwnerId");

            migrationBuilder.CreateIndex(
                name: "IX_SuSecretaryOwner_SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                column: "SuUserId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SuSecretary",
                schema: "SystemUtility");

            migrationBuilder.DropTable(
                name: "SuSecretaryAttachment",
                schema: "SystemUtility");

            migrationBuilder.DropTable(
                name: "SuSecretaryOwner",
                schema: "SystemUtility");
        }
    }
}
