// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RemoveRequiredFieldTor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_PeriodTypeCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate");

            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftTechnicalSpecifications_SuParameter_UnitCode",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications");

            migrationBuilder.AlterColumn<bool>(
                name: "HasWarranty",
                schema: "Procurement",
                table: "PpTorDraftWarranty",
                type: "boolean",
                nullable: true,
                oldClrType: typeof(bool),
                oldType: "boolean");

            migrationBuilder.AlterColumn<string>(
                name: "UnitCode",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "character varying(50)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(50)");

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<int>(
                name: "Quantity",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "StartDate",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<string>(
                name: "PersonalCount",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "EndDate",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<string>(
                name: "Branch",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(2000)",
                oldMaxLength: 2000);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftQualifications",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftQualifications",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<int>(
                name: "TermNumber",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<int>(
                name: "Period",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<decimal>(
                name: "Percent",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "numeric",
                nullable: true,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftObject",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftObject",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<decimal>(
                name: "Rate",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "numeric",
                nullable: true,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<string>(
                name: "PeriodTypeCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "character varying(50)",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(50)");

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<string>(
                name: "Department",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AlterColumn<string>(
                name: "BudgetType",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AlterColumn<decimal>(
                name: "Budget",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "numeric",
                nullable: true,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<string>(
                name: "AccountNo",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftBudget",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftBudget",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<decimal>(
                name: "BudgetAmount",
                schema: "Procurement",
                table: "PpTorDraftBudget",
                type: "numeric",
                nullable: true,
                oldClrType: typeof(decimal),
                oldType: "numeric");

            migrationBuilder.AlterColumn<bool>(
                name: "IsContractGuarantee",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "boolean",
                nullable: true,
                oldClrType: typeof(bool),
                oldType: "boolean");

            migrationBuilder.AlterColumn<Guid>(
                name: "DocumentTemplateId",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AlterColumn<bool>(
                name: "BidGuarantee",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "boolean",
                nullable: true,
                oldClrType: typeof(bool),
                oldType: "boolean");

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_PeriodTypeCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                column: "PeriodTypeCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftTechnicalSpecifications_SuParameter_UnitCode",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                column: "UnitCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_PeriodTypeCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate");

            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftTechnicalSpecifications_SuParameter_UnitCode",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications");

            migrationBuilder.AlterColumn<bool>(
                name: "HasWarranty",
                schema: "Procurement",
                table: "PpTorDraftWarranty",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "UnitCode",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "character varying(50)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Quantity",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "StartDate",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "PersonalCount",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTimeOffset>(
                name: "EndDate",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                oldClrType: typeof(DateTimeOffset),
                oldType: "timestamp with time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Branch",
                schema: "Procurement",
                table: "PpTorDraftTechnicalPeriodDetail",
                type: "character varying(2000)",
                maxLength: 2000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(2000)",
                oldMaxLength: 2000,
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftQualifications",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftQualifications",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "TermNumber",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Period",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "Percent",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "numeric",
                nullable: false,
                defaultValue: 0m,
                oldClrType: typeof(decimal),
                oldType: "numeric",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftObject",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftObject",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "Rate",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "numeric",
                nullable: false,
                defaultValue: 0m,
                oldClrType: typeof(decimal),
                oldType: "numeric",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "PeriodTypeCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                type: "character varying(50)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Department",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "BudgetType",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "Budget",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "numeric",
                nullable: false,
                defaultValue: 0m,
                oldClrType: typeof(decimal),
                oldType: "numeric",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AccountNo",
                schema: "Procurement",
                table: "PpTorDraftBudgetDetail",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<int>(
                name: "Sequence",
                schema: "Procurement",
                table: "PpTorDraftBudget",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                schema: "Procurement",
                table: "PpTorDraftBudget",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "BudgetAmount",
                schema: "Procurement",
                table: "PpTorDraftBudget",
                type: "numeric",
                nullable: false,
                defaultValue: 0m,
                oldClrType: typeof(decimal),
                oldType: "numeric",
                oldNullable: true);

            migrationBuilder.AlterColumn<bool>(
                name: "IsContractGuarantee",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldNullable: true);

            migrationBuilder.AlterColumn<Guid>(
                name: "DocumentTemplateId",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AlterColumn<bool>(
                name: "BidGuarantee",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftFineRate_SuParameter_PeriodTypeCode",
                schema: "Procurement",
                table: "PpTorDraftFineRate",
                column: "PeriodTypeCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftTechnicalSpecifications_SuParameter_UnitCode",
                schema: "Procurement",
                table: "PpTorDraftTechnicalSpecifications",
                column: "UnitCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
