// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddRentalApprovalDetail : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "BranchLocation",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "DistrictCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "DistrictName",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "ExpectedContractDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<decimal>(
                name: "MaxMonthlyRent",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "ProvinceCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ProvinceName",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "RentTypeCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "character varying(50)",
                nullable: false,
                defaultValue: "RentalTpl001");

            migrationBuilder.AddColumn<int>(
                name: "RentalDurationDay",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "RentalDurationMonth",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "RentalDurationYear",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "RentalEndDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<string>(
                name: "RentalLocationDetails",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "RentalStartDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<string>(
                name: "SubDistrictCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "SubDistrictName",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<decimal>(
                name: "TotalRentalAmount",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.CreateIndex(
                name: "IX_PPrincipleApprovalRental_RentTypeCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                column: "RentTypeCode");

            migrationBuilder.AddForeignKey(
                name: "FK_PPrincipleApprovalRental_SuParameter_RentTypeCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                column: "RentTypeCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PPrincipleApprovalRental_SuParameter_RentTypeCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropIndex(
                name: "IX_PPrincipleApprovalRental_RentTypeCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "BranchLocation",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "DistrictCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "DistrictName",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "ExpectedContractDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "MaxMonthlyRent",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "ProvinceCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "ProvinceName",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentTypeCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentalDurationDay",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentalDurationMonth",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentalDurationYear",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentalEndDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentalLocationDetails",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "RentalStartDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "SubDistrictCode",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "SubDistrictName",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "TotalRentalAmount",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");
        }
    }
}
