// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTelephone : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Telephone",
                schema: "Procurement",
                table: "Pw119",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Telephone",
                schema: "Procurement",
                table: "PPettyCash",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Telephone",
                schema: "Procurement",
                table: "P79Clause2",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Telephone",
                schema: "Procurement",
                table: "Pw119");

            migrationBuilder.DropColumn(
                name: "Telephone",
                schema: "Procurement",
                table: "PPettyCash");

            migrationBuilder.DropColumn(
                name: "Telephone",
                schema: "Procurement",
                table: "P79Clause2");
        }
    }
}
