// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCaContractDraftVendorEditTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CaContractDraftVendorEdit",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractDraftVendorId = table.Column<Guid>(type: "uuid", nullable: false),
                    ProcurementId = table.Column<Guid>(type: "uuid", nullable: false),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ContractInvitationVendorsId = table.Column<Guid>(type: "uuid", nullable: false),
                    Email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    ContractName = table.Column<string>(type: "text", nullable: false),
                    PoNumber = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    ContractDraftNumber = table.Column<string>(type: "text", nullable: false),
                    ContractNumber = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Budget = table.Column<decimal>(type: "numeric", nullable: false),
                    ContractSignedDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    ContractEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    ContractTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    TemplateCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    TemplateText = table.Column<string>(type: "text", nullable: true),
                    SubTemplateCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    SubTemplateText = table.Column<string>(type: "text", nullable: true),
                    StartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    EndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    IsWorkingDayOnly = table.Column<bool>(type: "boolean", nullable: false),
                    VendorAppointmentMemoDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    PeriodConditionTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    BuyerName = table.Column<string>(type: "text", nullable: true),
                    BuyerAddress = table.Column<string>(type: "text", nullable: true),
                    BuyerProvinceCode = table.Column<string>(type: "text", nullable: true),
                    BuyerProvinceName = table.Column<string>(type: "text", nullable: true),
                    BuyerDistrictCode = table.Column<string>(type: "text", nullable: true),
                    BuyerDistrictName = table.Column<string>(type: "text", nullable: true),
                    BuyerSubDistrictCode = table.Column<string>(type: "text", nullable: true),
                    BuyerSubDistrictName = table.Column<string>(type: "text", nullable: true),
                    VendorId = table.Column<Guid>(type: "uuid", nullable: false),
                    VendorStartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    VendorEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    VendorEstablishmentName = table.Column<string>(type: "text", nullable: true),
                    VendorRegistrationPlace = table.Column<string>(type: "text", nullable: true),
                    VendorAddress = table.Column<string>(type: "text", nullable: true),
                    VendorRoad = table.Column<string>(type: "text", nullable: true),
                    VendorRawProvinceCode = table.Column<string>(type: "text", nullable: true),
                    VendorRawDistrictCode = table.Column<string>(type: "text", nullable: true),
                    VendorRawSubDistrictCode = table.Column<string>(type: "text", nullable: true),
                    AgreementType = table.Column<string>(type: "text", nullable: true),
                    AgreementContractItem = table.Column<string>(type: "text", nullable: true),
                    IsAgreementExchangeGiver = table.Column<bool>(type: "boolean", nullable: true),
                    AgreementWorkplaceAddress = table.Column<string>(type: "text", nullable: true),
                    AgreementWorkplaceProvinceCode = table.Column<string>(type: "text", nullable: true),
                    AgreementWorkplaceProvinceName = table.Column<string>(type: "text", nullable: true),
                    AgreementWorkplaceDistrictCode = table.Column<string>(type: "text", nullable: true),
                    AgreementWorkplaceDistrictName = table.Column<string>(type: "text", nullable: true),
                    AgreementWorkplaceSubDistrictCode = table.Column<string>(type: "text", nullable: true),
                    AgreementWorkplaceSubDistrictName = table.Column<string>(type: "text", nullable: true),
                    AgreementRentalDurationYear = table.Column<int>(type: "integer", nullable: true),
                    AgreementRentalDurationMonth = table.Column<int>(type: "integer", nullable: true),
                    AgreementRentalDurationDay = table.Column<int>(type: "integer", nullable: true),
                    AgreementStartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    AgreementEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    AgreementBrand = table.Column<string>(type: "text", nullable: true),
                    AgreementModel = table.Column<string>(type: "text", nullable: true),
                    AgreementSerialNumber = table.Column<string>(type: "text", nullable: true),
                    AgreementEngineCapacityCc = table.Column<decimal>(type: "numeric", nullable: true),
                    AgreementQuantity = table.Column<int>(type: "integer", nullable: true),
                    AgreementUnitCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    AgreementVatRateType = table.Column<string>(type: "character varying(50)", nullable: true),
                    AgreementPrice = table.Column<decimal>(type: "numeric", nullable: true),
                    AgreementVatAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    AgreementTotalPrice = table.Column<decimal>(type: "numeric", nullable: true),
                    PaymentTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    PaymentDueDays = table.Column<int>(type: "integer", nullable: true),
                    PaymentRedeliveryDate = table.Column<string>(type: "character varying(50)", nullable: true),
                    DeliveryAddress = table.Column<string>(type: "text", nullable: true),
                    DeliveryDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    DeliveryLeadTime = table.Column<int>(type: "integer", nullable: true),
                    DeliveryLeadTimeTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    DeliveryLeadOtherTime = table.Column<int>(type: "integer", nullable: true),
                    DeliveryPeriodTypeCode = table.Column<string>(type: "text", nullable: true),
                    DeliveryLeadOtherTimeTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    DeliveryCountingConditionCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    TerminationStartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    TerminationEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    TerminationDurationYear = table.Column<int>(type: "integer", nullable: true),
                    TerminationDurationMonth = table.Column<int>(type: "integer", nullable: true),
                    TerminationDurationDay = table.Column<int>(type: "integer", nullable: true),
                    VendorProcessingTimePerYear = table.Column<int>(type: "integer", nullable: true),
                    VendorProcessingTimePerMonth = table.Column<int>(type: "integer", nullable: true),
                    VendorProcessingTimePerDay = table.Column<int>(type: "integer", nullable: true),
                    EgpResult = table.Column<bool>(type: "boolean", nullable: true),
                    EgpRemark = table.Column<string>(type: "text", nullable: true),
                    EgpDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    CoiResult = table.Column<bool>(type: "boolean", nullable: true),
                    CoiRemark = table.Column<string>(type: "text", nullable: true),
                    CoiDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    WatchlistResult = table.Column<bool>(type: "boolean", nullable: true),
                    WatchlistRemark = table.Column<string>(type: "text", nullable: true),
                    WatchlistDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    ContractStatus = table.Column<string>(type: "text", nullable: false, defaultValue: "Draft"),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftVendorEdit", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_AgreementUnitCode",
                        column: x => x.AgreementUnitCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_AgreementVatRateType",
                        column: x => x.AgreementVatRateType,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_ContractTypeCode",
                        column: x => x.ContractTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_DeliveryCountingCondi~",
                        column: x => x.DeliveryCountingConditionCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_DeliveryLeadOtherTime~",
                        column: x => x.DeliveryLeadOtherTimeTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_DeliveryLeadTimeTypeC~",
                        column: x => x.DeliveryLeadTimeTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_PaymentRedeliveryDate",
                        column: x => x.PaymentRedeliveryDate,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_PaymentTypeCode",
                        column: x => x.PaymentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_PeriodConditionTypeCo~",
                        column: x => x.PeriodConditionTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_SubTemplateCode",
                        column: x => x.SubTemplateCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuParameter_TemplateCode",
                        column: x => x.TemplateCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEdit_SuVendor_VendorId",
                        column: x => x.VendorId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuVendor",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditAcceptor",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true),
                    Type = table.Column<string>(type: "text", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    EmployeeCode = table.Column<string>(type: "text", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    BusinessUnitName = table.Column<string>(type: "text", nullable: false),
                    PositionName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    DelegateeId = table.Column<Guid>(type: "uuid", nullable: true),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ActionAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    IsCurrent = table.Column<bool>(type: "boolean", nullable: false),
                    SendToAcceptorId = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditAcceptor", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditAcceptor_CaContractDraftVendorEdit_CaCon~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditAcceptor_SuDelegatee_DelegateeId",
                        column: x => x.DelegateeId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuDelegatee",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditAcceptor_SuUser_SendToAcceptorId",
                        column: x => x.SendToAcceptorId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditAcceptor_SuUser_UserId",
                        column: x => x.UserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditEquipmentRental",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    CopierNumberOfMachines = table.Column<int>(type: "integer", nullable: true),
                    CopierRentalQuantity = table.Column<int>(type: "integer", nullable: true),
                    CopierMonthlyRentalRate = table.Column<int>(type: "integer", nullable: true),
                    CopierEstimatedMonthlyCopyVolume = table.Column<int>(type: "integer", nullable: true),
                    CopierActualMonthlyCopyVolume = table.Column<int>(type: "integer", nullable: true),
                    CopierCopyRatePerPage = table.Column<int>(type: "integer", nullable: true),
                    CarRentPerVehicle = table.Column<decimal>(type: "numeric", nullable: true),
                    CarUnitCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    LeaseDurationYear = table.Column<int>(type: "integer", nullable: true),
                    LeaseDurationMonth = table.Column<int>(type: "integer", nullable: true),
                    LeaseDurationDay = table.Column<int>(type: "integer", nullable: true),
                    LeaseCountFromCondition = table.Column<string>(type: "character varying(50)", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditEquipmentRental", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditEquipmentRental_CaContractDraftVendorEdi~",
                        column: x => x.ContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditEquipmentRental_SuParameter_CarUnitCode",
                        column: x => x.CarUnitCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditEquipmentRental_SuParameter_LeaseCountFr~",
                        column: x => x.LeaseCountFromCondition,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditPaymentTerm",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    PaymentTermNo = table.Column<int>(type: "integer", nullable: true),
                    LeadTime = table.Column<int>(type: "integer", nullable: true),
                    DeliveryDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    InstallmentPercentage = table.Column<decimal>(type: "numeric", nullable: true),
                    Amount = table.Column<decimal>(type: "numeric", nullable: true),
                    AdvanceDeductionAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    PerformanceDeductionAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    Description = table.Column<string>(type: "text", nullable: true),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    PeriodTypeCode = table.Column<string>(type: "character varying(50)", nullable: false, defaultValue: "PeriodType001"),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditPaymentTerm", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditPaymentTerm_CaContractDraftVendorEdit_Ca~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditPaymentTerm_SuParameter_PeriodTypeCode",
                        column: x => x.PeriodTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditTermsConditions",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    DefectWarrantyTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    AdvancePaymentIsIncluded = table.Column<bool>(type: "boolean", nullable: true),
                    AdvancePaymentAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    AdvancePaymentPercentage = table.Column<decimal>(type: "numeric", nullable: true),
                    AdvancePaymentDueDate = table.Column<int>(type: "integer", nullable: true),
                    AdvancePaymentConditionCode = table.Column<string>(type: "text", nullable: true),
                    HasWarranty = table.Column<bool>(type: "boolean", nullable: true),
                    WarrantyPeriodYear = table.Column<int>(type: "integer", nullable: true),
                    WarrantyPeriodMonth = table.Column<int>(type: "integer", nullable: true),
                    WarrantyPeriodDay = table.Column<int>(type: "integer", nullable: true),
                    WarrantyConditionCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    FixingDeadlinePeriodYear = table.Column<int>(type: "integer", nullable: true),
                    FixingDeadlinePeriodMonth = table.Column<int>(type: "integer", nullable: true),
                    FixingDeadlinePeriodDay = table.Column<int>(type: "integer", nullable: true),
                    WarrantyMonthlyAllowedDowntimeHours = table.Column<int>(type: "integer", nullable: true),
                    WarrantyDowntimePercentPerMonth = table.Column<decimal>(type: "numeric", nullable: true),
                    WarrantyPenaltyPerHour = table.Column<decimal>(type: "numeric", nullable: true),
                    DowntimeResolutionHours = table.Column<int>(type: "integer", nullable: true),
                    DowntimeResolutionDay = table.Column<int>(type: "integer", nullable: true),
                    RepairCompletionHours = table.Column<int>(type: "integer", nullable: true),
                    RepairCompletionDay = table.Column<int>(type: "integer", nullable: true),
                    RepairDelayPenaltyPercentPerHour = table.Column<decimal>(type: "numeric", nullable: true),
                    Warranty_MaxMonthlyMalfunction = table.Column<int>(type: "integer", nullable: true),
                    Warranty_MaxMonthlyMalfunctionTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    Warranty_MaxMonthlyMalfunctionRate = table.Column<decimal>(type: "numeric", nullable: true),
                    Warranty_MaxMonthlyMalfunctionPenaltyPercentageRate = table.Column<decimal>(type: "numeric", nullable: true),
                    Warranty_MaxMonthlyMalfunctionPenaltyPerHour = table.Column<decimal>(type: "numeric", nullable: true),
                    Warranty_MaxMonthlyMalfunctionPenaltyDueDays = table.Column<int>(type: "integer", nullable: true),
                    Warranty_WarrantyStartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Warranty_WarrantyEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Warranty_WarrantyMaintenanceCount = table.Column<int>(type: "integer", nullable: true),
                    Warranty_WarrantyMaintenanceTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    PenaltyTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    PenaltyRate = table.Column<decimal>(type: "numeric", nullable: true),
                    PenaltyAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    PenaltyRateTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    IsGuaranteeSubmitted = table.Column<bool>(type: "boolean", nullable: true),
                    GuaranteeTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    GuaranteeAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    GuaranteePercentage = table.Column<decimal>(type: "numeric", nullable: true),
                    GuaranteeReferenceNumber = table.Column<string>(type: "text", nullable: true),
                    GuaranteeDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    GuaranteeBank = table.Column<string>(type: "character varying(50)", nullable: true),
                    GuaranteeBankBranch = table.Column<string>(type: "text", nullable: true),
                    GuaranteeBankAccountNumber = table.Column<string>(type: "text", nullable: true),
                    GuaranteeBankCollateralStartDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    GuaranteeBankCollateralEndDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    GuaranteeOtherDetails = table.Column<string>(type: "text", nullable: true),
                    RetentionIsIncluded = table.Column<bool>(type: "boolean", nullable: true),
                    RetentionPaymentAmount = table.Column<decimal>(type: "numeric", nullable: true),
                    RetentionPaymentPercentage = table.Column<decimal>(type: "numeric", nullable: true),
                    RedeliveryCorrectionType = table.Column<string>(type: "text", nullable: true),
                    RedeliveryCorrectionDescription = table.Column<string>(type: "text", nullable: true),
                    RedeliveryCorrectionRentalDurationYear = table.Column<int>(type: "integer", nullable: true),
                    RedeliveryCorrectionRentalDurationMonth = table.Column<int>(type: "integer", nullable: true),
                    RedeliveryCorrectionRentalDurationDay = table.Column<int>(type: "integer", nullable: true),
                    RedeliveryCorrectionDeadline = table.Column<int>(type: "integer", nullable: true),
                    RedeliveryCorrectionDeadlineTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    RedeliveryCorrectionDue = table.Column<int>(type: "integer", nullable: true),
                    RedeliveryCorrectionDueTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditTermsConditions", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_CaContractDraftVendorEdi~",
                        column: x => x.ContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_DefectWarran~",
                        column: x => x.DefectWarrantyTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code");
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_GuaranteeBank",
                        column: x => x.GuaranteeBank,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_GuaranteeTyp~",
                        column: x => x.GuaranteeTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_PenaltyRateT~",
                        column: x => x.PenaltyRateTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_PenaltyTypeC~",
                        column: x => x.PenaltyTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_RedeliveryCo~",
                        column: x => x.RedeliveryCorrectionDueTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_RedeliveryC~1",
                        column: x => x.RedeliveryCorrectionDeadlineTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_WarrantyCond~",
                        column: x => x.WarrantyConditionCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_Warranty_Max~",
                        column: x => x.Warranty_MaxMonthlyMalfunctionTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditTermsConditions_SuParameter_Warranty_War~",
                        column: x => x.Warranty_WarrantyMaintenanceTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorChecker",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    CheckType = table.Column<string>(type: "text", nullable: false),
                    Result = table.Column<string>(type: "text", nullable: false),
                    ResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorChecker", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorChecker_CaContractDraftVendorEdit_~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorCheckerAttachments",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    Type = table.Column<string>(type: "text", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "text", nullable: false),
                    IsPublic = table.Column<bool>(type: "boolean", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false, defaultValue: 1),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorCheckerAttachments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorCheckerAttachments_CaContractDraft~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorCheckerAttachments_SuParameter_Doc~",
                        column: x => x.DocumentTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorDocumentHistory",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    DocumentType = table.Column<string>(type: "text", nullable: false),
                    StatusState = table.Column<string>(type: "text", nullable: false),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    FileId = table.Column<Guid>(type: "uuid", nullable: false),
                    Version = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    IsReplaced = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorDocumentHistory", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorDocumentHistory_CaContractDraftVen~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorsAttachment",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    TypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    Description = table.Column<string>(type: "text", nullable: true),
                    PageNumber = table.Column<int>(type: "integer", nullable: true),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    FormatOtherName = table.Column<string>(type: "text", nullable: true),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorsAttachment", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorsAttachment_CaContractDraftVendorE~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorsAttachment_SuParameter_TypeCode",
                        column: x => x.TypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorShareholders",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: true),
                    TaxId = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    FirstName = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    LastName = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    IsDirectorOr20PctShareholder = table.Column<bool>(type: "boolean", nullable: true),
                    WatchlistResult = table.Column<bool>(type: "boolean", nullable: true),
                    WatchlistResultRemark = table.Column<string>(type: "text", nullable: true),
                    WatchlistResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    CoiResult = table.Column<bool>(type: "boolean", nullable: true),
                    CoiResultRemark = table.Column<string>(type: "text", nullable: true),
                    CoiResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    EgpResult = table.Column<bool>(type: "boolean", nullable: true),
                    EgpRemark = table.Column<string>(type: "text", nullable: true),
                    EgpResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorShareholders", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorShareholders_CaContractDraftVendor~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftVendorEditAssignee",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true),
                    Group = table.Column<string>(type: "text", nullable: false),
                    Type = table.Column<string>(type: "text", nullable: false),
                    UserId = table.Column<Guid>(type: "uuid", nullable: false),
                    EmployeeCode = table.Column<string>(type: "text", nullable: false),
                    FullName = table.Column<string>(type: "text", nullable: false),
                    PositionName = table.Column<string>(type: "text", nullable: false),
                    BusinessUnitName = table.Column<string>(type: "text", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    DelegateeId = table.Column<Guid>(type: "uuid", nullable: true),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ActionAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    SendToAcceptorId = table.Column<Guid>(type: "uuid", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftVendorEditAssignee", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEditAssignee_CaContractDraftVendorEdit~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEditAssignee_SuDelegatee_DelegateeId",
                        column: x => x.DelegateeId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuDelegatee",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEditAssignee_SuUser_SendToAcceptorId",
                        column: x => x.SendToAcceptorId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEditAssignee_SuUser_UserId",
                        column: x => x.UserId,
                        principalSchema: "SystemUtility",
                        principalTable: "SuUser",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftVendorEditComponent",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    ComponentCode = table.Column<string>(type: "text", nullable: false),
                    ComponentName = table.Column<string>(type: "text", nullable: false),
                    IsEdited = table.Column<bool>(type: "boolean", nullable: false),
                    CaContractDraftVendorEditId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftVendorEditComponent", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftVendorEditComponent_CaContractDraftVendorEdi~",
                        column: x => x.CaContractDraftVendorEditId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftVendorEdit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorsAttachmentFile",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    FileName = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    FileType = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    CaContractDraftEditVendorsAttachmentId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorsAttachmentFile", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorsAttachmentFile_CaContractDraftEdi~",
                        column: x => x.CaContractDraftEditVendorsAttachmentId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftEditVendorsAttachment",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CaContractDraftEditVendorShareholderChecker",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ContractDraftEditVendorShareholdersId = table.Column<Guid>(type: "uuid", nullable: false),
                    CheckType = table.Column<string>(type: "text", nullable: false),
                    Result = table.Column<string>(type: "text", nullable: false),
                    ResultAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    Remark = table.Column<string>(type: "text", nullable: true),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CaContractDraftEditVendorShareholderChecker", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CaContractDraftEditVendorShareholderChecker_CaContractDraft~",
                        column: x => x.ContractDraftEditVendorShareholdersId,
                        principalSchema: "ContractManagement",
                        principalTable: "CaContractDraftEditVendorShareholders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditAcceptor_CaContractDraftVendorEditId",
                schema: "ContractManagement",
                table: "CaContractDraftEditAcceptor",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditAcceptor_DelegateeId",
                schema: "ContractManagement",
                table: "CaContractDraftEditAcceptor",
                column: "DelegateeId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditAcceptor_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CaContractDraftEditAcceptor",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditAcceptor_UserId",
                schema: "ContractManagement",
                table: "CaContractDraftEditAcceptor",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditEquipmentRental_CarUnitCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditEquipmentRental",
                column: "CarUnitCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditEquipmentRental_ContractDraftVendorEditId",
                schema: "ContractManagement",
                table: "CaContractDraftEditEquipmentRental",
                column: "ContractDraftVendorEditId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditEquipmentRental_LeaseCountFromCondition",
                schema: "ContractManagement",
                table: "CaContractDraftEditEquipmentRental",
                column: "LeaseCountFromCondition");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditPaymentTerm_CaContractDraftVendorEditId",
                schema: "ContractManagement",
                table: "CaContractDraftEditPaymentTerm",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditPaymentTerm_PeriodTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditPaymentTerm",
                column: "PeriodTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_ContractDraftVendorEditId",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "ContractDraftVendorEditId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_DefectWarrantyTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "DefectWarrantyTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_GuaranteeBank",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "GuaranteeBank");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_GuaranteeTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "GuaranteeTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_PenaltyRateTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "PenaltyRateTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_PenaltyTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "PenaltyTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_RedeliveryCorrectionDead~",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "RedeliveryCorrectionDeadlineTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_RedeliveryCorrectionDueT~",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "RedeliveryCorrectionDueTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_Warranty_MaxMonthlyMalfu~",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "Warranty_MaxMonthlyMalfunctionTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_Warranty_WarrantyMainten~",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "Warranty_WarrantyMaintenanceTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditTermsConditions_WarrantyConditionCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditTermsConditions",
                column: "WarrantyConditionCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorChecker_CaContractDraftVendorEditId",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorChecker",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorCheckerAttachments_CaContractDraft~",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorCheckerAttachments",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorCheckerAttachments_DocumentTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorCheckerAttachments",
                column: "DocumentTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorDocumentHistory_CaContractDraftVen~",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorDocumentHistory",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorsAttachment_CaContractDraftVendorE~",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorsAttachment",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorsAttachment_TypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorsAttachment",
                column: "TypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorsAttachmentFile_CaContractDraftEdi~",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorsAttachmentFile",
                column: "CaContractDraftEditVendorsAttachmentId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorShareholderChecker_ContractDraftEd~",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorShareholderChecker",
                column: "ContractDraftEditVendorShareholdersId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftEditVendorShareholders_CaContractDraftVendor~",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorShareholders",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_AgreementUnitCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "AgreementUnitCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_AgreementVatRateType",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "AgreementVatRateType");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_ContractTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "ContractTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_DeliveryCountingConditionCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "DeliveryCountingConditionCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_DeliveryLeadOtherTimeTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "DeliveryLeadOtherTimeTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_DeliveryLeadTimeTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "DeliveryLeadTimeTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_PaymentRedeliveryDate",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "PaymentRedeliveryDate");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_PaymentTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "PaymentTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_PeriodConditionTypeCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "PeriodConditionTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_SubTemplateCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "SubTemplateCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_TemplateCode",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "TemplateCode");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEdit_VendorId",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                column: "VendorId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEditAssignee_CaContractDraftVendorEdit~",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEditAssignee",
                column: "CaContractDraftVendorEditId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEditAssignee_DelegateeId",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEditAssignee",
                column: "DelegateeId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEditAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEditAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEditAssignee_UserId",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEditAssignee",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_CaContractDraftVendorEditComponent_CaContractDraftVendorEdi~",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEditComponent",
                column: "CaContractDraftVendorEditId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CaContractDraftEditAcceptor",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditEquipmentRental",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditPaymentTerm",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditTermsConditions",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorChecker",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorCheckerAttachments",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorDocumentHistory",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorsAttachmentFile",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorShareholderChecker",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftVendorEditAssignee",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftVendorEditComponent",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorsAttachment",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftEditVendorShareholders",
                schema: "ContractManagement");

            migrationBuilder.DropTable(
                name: "CaContractDraftVendorEdit",
                schema: "ContractManagement");
        }
    }
}
