// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RenameIsDirectorAndAddIsShareholderInShareholderTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders");

            migrationBuilder.RenameColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "SystemUtility",
                table: "SuVendorShareholders",
                newName: "IsShareholder");

            migrationBuilder.RenameColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "Procurement",
                table: "PPurchaseOrderEntrepreneurShareholders",
                newName: "IsShareholder");

            migrationBuilder.RenameColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "Procurement",
                table: "PInvitedEntrepreneurShareholders",
                newName: "IsShareholder");

            migrationBuilder.RenameColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholders",
                newName: "IsShareholder");

            migrationBuilder.RenameColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "ContractAgreement",
                table: "CaContractDraftVendorShareholders",
                newName: "IsShareholder");

            migrationBuilder.RenameColumn(
                name: "IsDirectorOr20PctShareholder",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorShareholders",
                newName: "IsShareholder");

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "SystemUtility",
                table: "SuVendorShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "Procurement",
                table: "PPurchaseOrderEntrepreneurShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsShareholder",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "Procurement",
                table: "PInvitedEntrepreneurShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "ContractAgreement",
                table: "CaContractDraftVendorShareholders",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDirector",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorShareholders",
                type: "boolean",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "SystemUtility",
                table: "SuVendorShareholders");

            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "Procurement",
                table: "PPurchaseOrderEntrepreneurShareholders");

            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders");

            migrationBuilder.DropColumn(
                name: "IsShareholder",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders");

            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "Procurement",
                table: "PInvitedEntrepreneurShareholders");

            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholders");

            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "ContractAgreement",
                table: "CaContractDraftVendorShareholders");

            migrationBuilder.DropColumn(
                name: "IsDirector",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorShareholders");

            migrationBuilder.RenameColumn(
                name: "IsShareholder",
                schema: "SystemUtility",
                table: "SuVendorShareholders",
                newName: "IsDirectorOr20PctShareholder");

            migrationBuilder.RenameColumn(
                name: "IsShareholder",
                schema: "Procurement",
                table: "PPurchaseOrderEntrepreneurShareholders",
                newName: "IsDirectorOr20PctShareholder");

            migrationBuilder.RenameColumn(
                name: "IsShareholder",
                schema: "Procurement",
                table: "PInvitedEntrepreneurShareholders",
                newName: "IsDirectorOr20PctShareholder");

            migrationBuilder.RenameColumn(
                name: "IsShareholder",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholders",
                newName: "IsDirectorOr20PctShareholder");

            migrationBuilder.RenameColumn(
                name: "IsShareholder",
                schema: "ContractAgreement",
                table: "CaContractDraftVendorShareholders",
                newName: "IsDirectorOr20PctShareholder");

            migrationBuilder.RenameColumn(
                name: "IsShareholder",
                schema: "ContractManagement",
                table: "CaContractDraftEditVendorShareholders",
                newName: "IsDirectorOr20PctShareholder");

            migrationBuilder.AddColumn<bool>(
                name: "IsDirectorOr20PctShareholder",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }
    }
}
