// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddColumnToCaContractDraftTermsConditions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "DowntimeResolutionDay",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DowntimeResolutionHours",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RepairCompletionDay",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RepairCompletionHours",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "RepairDelayPenaltyPercentPerHour",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "numeric",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "WarrantyDowntimePercentPerMonth",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "numeric",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "WarrantyMonthlyAllowedDowntimeHours",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "WarrantyPenaltyPerHour",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions",
                type: "numeric",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DowntimeResolutionDay",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "DowntimeResolutionHours",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "RepairCompletionDay",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "RepairCompletionHours",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "RepairDelayPenaltyPercentPerHour",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "WarrantyDowntimePercentPerMonth",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "WarrantyMonthlyAllowedDowntimeHours",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");

            migrationBuilder.DropColumn(
                name: "WarrantyPenaltyPerHour",
                schema: "ContractAgreement",
                table: "CaContractDraftTermsConditions");
        }
    }
}
