// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddColumnIsMA : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsMA",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail",
                type: "boolean",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsMA",
                schema: "Procurement",
                table: "PpPurchaseRequisitionPaymentTerm",
                type: "boolean",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsMA",
                schema: "Procurement",
                table: "PpTorDraftPaymentTermDetail");

            migrationBuilder.DropColumn(
                name: "IsMA",
                schema: "Procurement",
                table: "PpPurchaseRequisitionPaymentTerm");
        }
    }
}
