// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddIsPositionTypeAndBusinessUnitToSuSecretaryOwner : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SuSecretaryOwner_SuUser_SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner");

            migrationBuilder.AlterColumn<Guid>(
                name: "SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddColumn<string>(
                name: "BusinessUnitId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "BusinessUnitName",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsPositionType",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddForeignKey(
                name: "FK_SuSecretaryOwner_SuUser_SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                column: "SuUserId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SuSecretaryOwner_SuUser_SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner");

            migrationBuilder.DropColumn(
                name: "BusinessUnitId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner");

            migrationBuilder.DropColumn(
                name: "BusinessUnitName",
                schema: "SystemUtility",
                table: "SuSecretaryOwner");

            migrationBuilder.DropColumn(
                name: "IsPositionType",
                schema: "SystemUtility",
                table: "SuSecretaryOwner");

            migrationBuilder.AlterColumn<Guid>(
                name: "SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_SuSecretaryOwner_SuUser_SuUserId",
                schema: "SystemUtility",
                table: "SuSecretaryOwner",
                column: "SuUserId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
