// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class UpdatePettyCashGLAccountParameters : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                -- ============================================
                -- PettyCashStandardType (15.3.1)
                -- ============================================

                -- (4) ค่าของขวัญ -> 5253010007
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Values"" = '{""GLAccount094"": {""Value"": ""5253010007 : คชจ.ค่าของขวัญ"", ""Sequence"": 1}}'::jsonb
                WHERE ""Id"" = 'eba04d53-9bab-4840-b3bd-bda01d5afecd'::uuid;

                -- (7) ค่าสิ่งพิมพ์ต่างๆ -> 5253010003
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Values"" = '{""GLAccount090"": {""Value"": ""5253010003 : คชจ.สิ่งพิมพ์โฆษณา"", ""Sequence"": 1}}'::jsonb
                WHERE ""Id"" = '1b78f53b-774c-4333-82e9-ec5bd9527773'::uuid;

                -- (8) ค่าใช้จ่ายเบ็ดเตล็ด -> 5253010999
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Values"" = '{""GLAccount133"": {""Value"": ""5253010999 : คชจ.เบ็ดเตล็ดอื่นๆ"", ""Sequence"": 1}}'::jsonb
                WHERE ""Id"" = '13792e3c-41eb-4795-99e2-9ff325ae21c2'::uuid;

                -- (9) ค่าอะไหล่หรือวัสดุที่ใช้ในการซ่อมแซม -> 5252015001-005
                INSERT INTO ""SystemUtility"".""SuParameter""
                (""Id"", ""ParentId"", ""Code"", ""Sequence"", ""Label"", ""IsActive"", ""IsDeleted"", ""CreatedBy"", ""CreatedAt"", ""CreatedByName"", ""LastModifiedBy"", ""LastModifiedAt"", ""LastModifiedByName"", ""GroupCode"", ""Values"")
                SELECT
                    '659f5c20-8f44-4540-a31e-3bc6fecd4067'::uuid, NULL, 'PettyCashStandardType005', 4, '(9) ค่าอะไหล่หรือวัสดุที่ใช้ในการซ่อมแซม', true, false,
                    '00000000-0000-0000-0000-000000000000'::uuid, '2025-08-05 22:27:59.820', 'System Migration',
                    '9da5c017-2ce5-44f2-805c-3d4505deab23'::uuid, '2026-06-12 19:21:12.239', 'มธุร****16451 ปราบ****16451',
                    'PettyCashStandardType',
                    '{""GLAccount081"": {""Value"": ""5252015001 : ค่าบำรุง-ตกแต่งฯ"", ""Sequence"": 1}, ""GLAccount082"": {""Value"": ""5252015002 : ค่าบำรุง-ซ่อมแซมฯ"", ""Sequence"": 2}, ""GLAccount083"": {""Value"": ""5252015003 : ค่าบำรุง-เครื่องจักร"", ""Sequence"": 3}, ""GLAccount084"": {""Value"": ""5252015004 : ค่าบำรุง-เครื่องใช้ฯ"", ""Sequence"": 4}, ""GLAccount085"": {""Value"": ""5252015005 : ค่าบำรุง-ยานพาหนะ"", ""Sequence"": 5}}'::jsonb
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM ""SystemUtility"".""SuParameter""
                    WHERE ""Code"" = 'PettyCashStandardType005'
                      AND ""GroupCode"" = 'PettyCashStandardType'
                );

                -- (10) ค่าจ้างหรือจ้างเหมา (อะไหล่รวมกับค่าแรง) -> 5252015001-005
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Sequence"" = 5, ""Values"" = '{""GLAccount081"": {""Value"": ""5252015001 : ค่าบำรุง-ตกแต่งฯ"", ""Sequence"": 1}, ""GLAccount082"": {""Value"": ""5252015002 : ค่าบำรุง-ซ่อมแซมฯ"", ""Sequence"": 2}, ""GLAccount083"": {""Value"": ""5252015003 : ค่าบำรุง-เครื่องจักร"", ""Sequence"": 3}, ""GLAccount084"": {""Value"": ""5252015004 : ค่าบำรุง-เครื่องใช้ฯ"", ""Sequence"": 4}, ""GLAccount085"": {""Value"": ""5252015005 : ค่าบำรุง-ยานพาหนะ"", ""Sequence"": 5}}'::jsonb
                WHERE ""Id"" = '7e0db0f3-5739-4af4-bb10-3cfc83ae2150'::uuid;


                -- ============================================
                -- PettyCashConvenienceType (15.3.2)
                -- ============================================

                -- (1) ค่าเครื่องเขียนแบบพิมพ์ -> 5252010018
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Values"" = '{""GLAccount066"": {""Value"": ""5252010018 : ค่าวัสดุเครื่องเขียน"", ""Sequence"": 1}}'::jsonb
                WHERE ""Id"" = '6f9695ad-8d53-41cd-b253-eeaf070246ff'::uuid;

                -- (2) ค่าเครื่องใช้สำนักงาน -> 1451510001 + 5252010020
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Values"" = '{""GLAccount004"": {""Value"": ""1451510001 : เครื่องใช้สำนักงาน"", ""Sequence"": 1}, ""GLAccount068"": {""Value"": ""5252010020 : เครื่องใช้สนง.จ่าย"", ""Sequence"": 2}}'::jsonb
                WHERE ""Id"" = '42399556-20e0-4ced-9a2d-d26dfb7d50a4'::uuid;

                -- (3) ค่าวัสดุของใช้สิ้นเปลือง -> 5252010019
                UPDATE ""SystemUtility"".""SuParameter""
                SET ""Values"" = '{""GLAccount067"": {""Value"": ""5252010019 : ค่าวัสดุสิ้นเปลือง"", ""Sequence"": 1}}'::jsonb
                WHERE ""Id"" = '432301fa-5853-44fd-97ef-a358f686930a'::uuid;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
