// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDetailOnContractDraftVendor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "VendorAddress",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "VendorEstablishmentName",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "VendorRawDistrictCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "VendorRawProvinceCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "VendorRawSubDistrictCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "VendorRoad",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "VendorAddress",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "VendorEstablishmentName",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "VendorRawDistrictCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "VendorRawProvinceCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "VendorRawSubDistrictCode",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");

            migrationBuilder.DropColumn(
                name: "VendorRoad",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");
        }
    }
}
