// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDisbursementApprovalBudget : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CmDisbursementApprovalBudget",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CmDisbursementApprovalId = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    Department = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    BudgetTypeCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    ProjectCode = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    AccountNoCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    Budget = table.Column<decimal>(type: "numeric", nullable: false),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CmDisbursementApprovalBudget", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CmDisbursementApprovalBudget_CmDisbursementApproval_CmDisbu~",
                        column: x => x.CmDisbursementApprovalId,
                        principalSchema: "ContractManagement",
                        principalTable: "CmDisbursementApproval",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CmDisbursementApprovalBudget_SuParameter_AccountNoCode",
                        column: x => x.AccountNoCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CmDisbursementApprovalBudget_SuParameter_BudgetTypeCode",
                        column: x => x.BudgetTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CmDisbursementApprovalBudget_AccountNoCode",
                schema: "ContractManagement",
                table: "CmDisbursementApprovalBudget",
                column: "AccountNoCode");

            migrationBuilder.CreateIndex(
                name: "IX_CmDisbursementApprovalBudget_BudgetTypeCode",
                schema: "ContractManagement",
                table: "CmDisbursementApprovalBudget",
                column: "BudgetTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CmDisbursementApprovalBudget_CmDisbursementApprovalId",
                schema: "ContractManagement",
                table: "CmDisbursementApprovalBudget",
                column: "CmDisbursementApprovalId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CmDisbursementApprovalBudget",
                schema: "ContractManagement");
        }
    }
}
