// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDesctipyion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ContractDescription",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "GuranteeDescription",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ProofOfPaymentDescription",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ContractDescription",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn");

            migrationBuilder.DropColumn(
                name: "GuranteeDescription",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn");

            migrationBuilder.DropColumn(
                name: "ProofOfPaymentDescription",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn");
        }
    }
}
