// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddColumnDocumentTemplateCode : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "DocumentTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors",
                type: "character varying(50)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_CaContractInvitationVendors_DocumentTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors",
                column: "DocumentTemplateCode");

            migrationBuilder.AddForeignKey(
                name: "FK_CaContractInvitationVendors_SuParameter_DocumentTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors",
                column: "DocumentTemplateCode",
                principalSchema: "SystemUtility",
                principalTable: "SuParameter",
                principalColumn: "Code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CaContractInvitationVendors_SuParameter_DocumentTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors");

            migrationBuilder.DropIndex(
                name: "IX_CaContractInvitationVendors_DocumentTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors");

            migrationBuilder.DropColumn(
                name: "DocumentTemplateCode",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors");
        }
    }
}
