// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCheckTypeToShareholderTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "CheckType",
                schema: "Procurement",
                table: "PPurchaseOrderEntrepreneurShareholders",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CheckType",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CheckType",
                schema: "Procurement",
                table: "PInvitedEntrepreneurShareholders",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CheckType",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholders",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CheckType",
                schema: "ContractAgreement",
                table: "CaContractDraftVendorShareholders",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CheckType",
                schema: "Procurement",
                table: "PPurchaseOrderEntrepreneurShareholders");

            migrationBuilder.DropColumn(
                name: "CheckType",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalEntrepreneursShareholders");

            migrationBuilder.DropColumn(
                name: "CheckType",
                schema: "Procurement",
                table: "PInvitedEntrepreneurShareholders");

            migrationBuilder.DropColumn(
                name: "CheckType",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendorShareholders");

            migrationBuilder.DropColumn(
                name: "CheckType",
                schema: "ContractAgreement",
                table: "CaContractDraftVendorShareholders");
        }
    }
}
