// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddFieldToP79Clause2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "DeliveryDate",
                schema: "Procurement",
                table: "P79Clause2",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ProcurementReasonItem1",
                schema: "Procurement",
                table: "P79Clause2",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ProcurementReasonItem2",
                schema: "Procurement",
                table: "P79Clause2",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DeliveryDate",
                schema: "Procurement",
                table: "P79Clause2");

            migrationBuilder.DropColumn(
                name: "ProcurementReasonItem1",
                schema: "Procurement",
                table: "P79Clause2");

            migrationBuilder.DropColumn(
                name: "ProcurementReasonItem2",
                schema: "Procurement",
                table: "P79Clause2");
        }
    }
}
