// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddColumnSendToAcceptorDate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Report",
                table: "RpContractCompletionByQuarter",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Report",
                table: "RpAuditAndRevenue",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "Pw184",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "Pw119",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPurchaseOrderApproval",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPurchaseOrder",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpTorDraft",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPrincipleApproval",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpPurchaseRequisition",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpMedianPrice",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPettyCashReimbursement",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPettyCash",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpAppoint",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PJp005",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PInvite",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PExpenseDisbursement",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "P79Clause2",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "CommitteeChanges",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriod",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CmContractTermination",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractAmendment",
                table: "CamCertificateRequisition",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "SendToAcceptorDate",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor",
                type: "timestamp with time zone",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Report",
                table: "RpContractCompletionByQuarter");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Report",
                table: "RpAuditAndRevenue");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "Pw184");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "Pw119");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPurchaseOrderApproval");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPurchaseOrder");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpTorDraft");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPrincipleApprovalRental");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPrincipleApproval");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpPurchaseRequisition");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpMedianPrice");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPettyCashReimbursement");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PPettyCash");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PpAppoint");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PJp005");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PInvite");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "PExpenseDisbursement");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "P79Clause2");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "Procurement",
                table: "CommitteeChanges");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriod");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CmContractTermination");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturn");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractAmendment",
                table: "CamCertificateRequisition");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractAgreement",
                table: "CaContractInvitationVendors");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractManagement",
                table: "CaContractDraftVendorEdit");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorDate",
                schema: "ContractAgreement",
                table: "CaContractDraftVendor");
        }
    }
}
