// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSendToAcceptorIdToAssigneeInfoEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUse~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration");

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderApprovalAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PpTorDraftAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PpPurchaseRequisitionAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PpMedianPriceAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPettyCashAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Plan",
                table: "PlanAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Plan",
                table: "PlanAnnouncementAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PExpenseDisbursementAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriodAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractTerminationAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenaltyAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentPoAddendumAssignee",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_PPurchaseOrderAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PPurchaseOrderApprovalAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderApprovalAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PpTorDraftAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PpTorDraftAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PPrincipleApprovalRentalAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PPrincipleApprovalAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PpPurchaseRequisitionAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PpPurchaseRequisitionAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PpMedianPriceAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PpMedianPriceAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PPettyCashAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPettyCashAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PlanAssignee_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PlanAnnouncementAssignee_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAnnouncementAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_PExpenseDisbursementAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PExpenseDisbursementAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CmDeliveryAcceptancePeriodAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriodAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CmContractTerminationAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractTerminationAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CmContractGuaranteeReturnAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentWaiveOrReducePenaltyAssignee_SendToAcce~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenaltyAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentPoAddendumAssignee_SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentPoAddendumAssignee",
                column: "SendToAcceptorId");

            migrationBuilder.CreateIndex(
                name: "IX_CamContractAmendmentExtendChangeAssigneeConfiguration_SendT~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                column: "SendToAcceptorId");

            migrationBuilder.AddForeignKey(
                name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUse~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUs~1",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                column: "UserId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_CamContractAmendmentPoAddendumAssignee_SuUser_SendToAccepto~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentPoAddendumAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_CamContractAmendmentWaiveOrReducePenaltyAssignee_SuUser_Sen~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenaltyAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_CmContractGuaranteeReturnAssignee_SuUser_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_CmContractTerminationAssignee_SuUser_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractTerminationAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_CmDeliveryAcceptancePeriodAssignee_SuUser_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriodAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PExpenseDisbursementAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PExpenseDisbursementAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PlanAnnouncementAssignee_SuUser_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAnnouncementAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PlanAssignee_SuUser_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PPettyCashAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPettyCashAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PpMedianPriceAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PpMedianPriceAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PpPurchaseRequisitionAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PpPurchaseRequisitionAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PPrincipleApprovalAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PPrincipleApprovalRentalAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PpTorDraftAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PpTorDraftAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PPurchaseOrderApprovalAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderApprovalAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_PPurchaseOrderAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderAssignee",
                column: "SendToAcceptorId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUse~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration");

            migrationBuilder.DropForeignKey(
                name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUs~1",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration");

            migrationBuilder.DropForeignKey(
                name: "FK_CamContractAmendmentPoAddendumAssignee_SuUser_SendToAccepto~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentPoAddendumAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_CamContractAmendmentWaiveOrReducePenaltyAssignee_SuUser_Sen~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenaltyAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_CmContractGuaranteeReturnAssignee_SuUser_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_CmContractTerminationAssignee_SuUser_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractTerminationAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_CmDeliveryAcceptancePeriodAssignee_SuUser_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriodAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PExpenseDisbursementAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PExpenseDisbursementAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PlanAnnouncementAssignee_SuUser_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAnnouncementAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PlanAssignee_SuUser_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PPettyCashAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPettyCashAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PpMedianPriceAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PpMedianPriceAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PpPurchaseRequisitionAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PpPurchaseRequisitionAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PPrincipleApprovalAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PPrincipleApprovalRentalAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PpTorDraftAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PpTorDraftAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PPurchaseOrderApprovalAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderApprovalAssignee");

            migrationBuilder.DropForeignKey(
                name: "FK_PPurchaseOrderAssignee_SuUser_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PPurchaseOrderAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PPurchaseOrderApprovalAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderApprovalAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PpTorDraftAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PpTorDraftAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PPrincipleApprovalRentalAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PPrincipleApprovalAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PpPurchaseRequisitionAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PpPurchaseRequisitionAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PpMedianPriceAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PpMedianPriceAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PPettyCashAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PPettyCashAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PlanAssignee_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PlanAnnouncementAssignee_SendToAcceptorId",
                schema: "Plan",
                table: "PlanAnnouncementAssignee");

            migrationBuilder.DropIndex(
                name: "IX_PExpenseDisbursementAssignee_SendToAcceptorId",
                schema: "Procurement",
                table: "PExpenseDisbursementAssignee");

            migrationBuilder.DropIndex(
                name: "IX_CmDeliveryAcceptancePeriodAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriodAssignee");

            migrationBuilder.DropIndex(
                name: "IX_CmContractTerminationAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractTerminationAssignee");

            migrationBuilder.DropIndex(
                name: "IX_CmContractGuaranteeReturnAssignee_SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAssignee");

            migrationBuilder.DropIndex(
                name: "IX_CamContractAmendmentWaiveOrReducePenaltyAssignee_SendToAcce~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenaltyAssignee");

            migrationBuilder.DropIndex(
                name: "IX_CamContractAmendmentPoAddendumAssignee_SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentPoAddendumAssignee");

            migrationBuilder.DropIndex(
                name: "IX_CamContractAmendmentExtendChangeAssigneeConfiguration_SendT~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPurchaseOrderApprovalAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PpTorDraftAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalRentalAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPrincipleApprovalAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PpPurchaseRequisitionAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PpMedianPriceAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PPettyCashAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Plan",
                table: "PlanAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Plan",
                table: "PlanAnnouncementAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "Procurement",
                table: "PExpenseDisbursementAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmDeliveryAcceptancePeriodAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractTerminationAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "ContractManagement",
                table: "CmContractGuaranteeReturnAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentWaiveOrReducePenaltyAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentPoAddendumAssignee");

            migrationBuilder.DropColumn(
                name: "SendToAcceptorId",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration");

            migrationBuilder.AddForeignKey(
                name: "FK_CamContractAmendmentExtendChangeAssigneeConfiguration_SuUse~",
                schema: "ContractAmendment",
                table: "CamContractAmendmentExtendChangeAssigneeConfiguration",
                column: "UserId",
                principalSchema: "SystemUtility",
                principalTable: "SuUser",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
