// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GHB.DP2.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTableContractManagement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ContractManagement",
                schema: "ContractManagement",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CaContractDraftVendorId = table.Column<Guid>(type: "uuid", nullable: false),
                    ProcurementId = table.Column<Guid>(type: "uuid", nullable: false),
                    Step = table.Column<string>(type: "text", nullable: false),
                    Status = table.Column<string>(type: "text", nullable: false),
                    ContractName = table.Column<string>(type: "text", nullable: false),
                    DepartmentId = table.Column<string>(type: "text", nullable: false),
                    SupplyMethodCode = table.Column<string>(type: "character varying(50)", nullable: false),
                    SupplyMethodTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    SupplyMethodSpecialTypeCode = table.Column<string>(type: "character varying(50)", nullable: true),
                    BudgetYear = table.Column<int>(type: "integer", nullable: false),
                    CreatedBy = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    CreatedByName = table.Column<string>(type: "text", nullable: false),
                    LastModifiedBy = table.Column<Guid>(type: "uuid", nullable: true),
                    LastModifiedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    LastModifiedByName = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ContractManagement", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ContractManagement_CaContractDraftVendor_CaContractDraftVen~",
                        column: x => x.CaContractDraftVendorId,
                        principalSchema: "ContractAgreement",
                        principalTable: "CaContractDraftVendor",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ContractManagement_Procurement_ProcurementId",
                        column: x => x.ProcurementId,
                        principalSchema: "Procurement",
                        principalTable: "Procurement",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ContractManagement_RawBusinessUnit_DepartmentId",
                        column: x => x.DepartmentId,
                        principalSchema: "Raws",
                        principalTable: "RawBusinessUnit",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ContractManagement_SuParameter_SupplyMethodCode",
                        column: x => x.SupplyMethodCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ContractManagement_SuParameter_SupplyMethodSpecialTypeCode",
                        column: x => x.SupplyMethodSpecialTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_ContractManagement_SuParameter_SupplyMethodTypeCode",
                        column: x => x.SupplyMethodTypeCode,
                        principalSchema: "SystemUtility",
                        principalTable: "SuParameter",
                        principalColumn: "Code",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ContractManagement_CaContractDraftVendorId",
                schema: "ContractManagement",
                table: "ContractManagement",
                column: "CaContractDraftVendorId");

            migrationBuilder.CreateIndex(
                name: "IX_ContractManagement_DepartmentId",
                schema: "ContractManagement",
                table: "ContractManagement",
                column: "DepartmentId");

            migrationBuilder.CreateIndex(
                name: "IX_ContractManagement_ProcurementId",
                schema: "ContractManagement",
                table: "ContractManagement",
                column: "ProcurementId");

            migrationBuilder.CreateIndex(
                name: "IX_ContractManagement_SupplyMethodCode",
                schema: "ContractManagement",
                table: "ContractManagement",
                column: "SupplyMethodCode");

            migrationBuilder.CreateIndex(
                name: "IX_ContractManagement_SupplyMethodSpecialTypeCode",
                schema: "ContractManagement",
                table: "ContractManagement",
                column: "SupplyMethodSpecialTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_ContractManagement_SupplyMethodTypeCode",
                schema: "ContractManagement",
                table: "ContractManagement",
                column: "SupplyMethodTypeCode");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ContractManagement",
                schema: "ContractManagement");
        }
    }
}
