<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import { Dialog } from 'primevue';
import { Button } from 'primevue';
import Editor from 'primevue/editor';
import { usePP006DetailStore } from '@/views/PP/stores/PP006/PP006Store';
import type { OnlyFileAttachment } from '@/models/shared/uploadFile';
import ST003Service from '@/services/file';
import { HttpStatusCode } from 'axios';
import { usePPDetailStore } from '@/stores/PP/ppStore';
import { numberToThaiText } from '@/helpers/currency';
import PP006Service from '@/views/PP/services/PP006/PP006Service';
import { PP006Status } from '@/views/PP/enums/pp006';
import ToastHelper from '@/helpers/toast';

const props = defineProps<{
  modelValue: boolean;
  entrepreneurId?: string;
}>();

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
}>();

const procurementStore = usePPDetailStore();
const store = usePP006DetailStore();
const email = ref('');
const files = ref<OnlyFileAttachment[]>([]);
const editorContent = ref('');
const isLoadingFiles = ref(false);

const entrepreneur = computed(() => {
  if (!props.entrepreneurId) return null;
  return store.detail.invitedEntrepreneurs.find(e => e.id === props.entrepreneurId);
});

const onClose = (): void => {
  email.value = '';
  editorContent.value = '';
  files.value = [];
  emit('update:modelValue', false);
};

const onSendEmail = async (): Promise<void> => {
  if (!props.entrepreneurId) return;

  await store.onSendEmailInviteAsync(props.entrepreneurId, email.value, editorContent.value, files.value);
  onClose();
};

const onFileSelect = async (event: Event): Promise<void> => {
  const target = event.target as HTMLInputElement;
  if (!target.files) return;

  const fileList = Array.from(target.files);

  for (const file of fileList) {
    const { data, status } = await ST003Service.uploadFile(file);

    if (status === HttpStatusCode.Ok) {
      const uploadedFile: OnlyFileAttachment = {
        fileId: data.id,
        fileName: file.name,
        sequence: files.value.length + 1,
      };

      files.value = [...files.value, uploadedFile];
    }
  }

  target.value = '';
};

const onRemoveFile = (index: number): void => {
  files.value.splice(index, 1);
};

watch(() => props.modelValue, async (newValue) => {
  if (newValue && entrepreneur.value) {
    email.value = entrepreneur.value.email || entrepreneur.value.entrepreneurEmail || '';

    const budget = procurementStore.procurementDetail.budget || 0;
    const guarantee = budget * 0.05;
    const budgetThaiText = numberToThaiText(budget);
    const guaranteeThaiText = numberToThaiText(guarantee);

    let template = entrepreneur.value.emailTemplate;

    if (!template && props.entrepreneurId) {
      template = await store.onGetDefaultEmailTemplateAsync(props.entrepreneurId);
    }

    editorContent.value = template || `<p>เรียน&nbsp;&nbsp;${entrepreneur.value.entrepreneurName || 'name'}&nbsp;จำกัด</p></br><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ตามที่ธนาคารอาคารสงเคราะห์[PNG]&nbsp;${procurementStore.procurementDetail.planName || 'PlanName'}&nbsp;โดยวิธี&nbsp;${procurementStore.procurementDetail.supplyMethodSpecialType || 'Supplymethode'}&nbsp;กับ&nbsp;${entrepreneur.value.entrepreneurName || 'name'}&nbsp;ได้เสนิราคาเป็นเงินทั้งสิ้น&nbsp;${budget.toLocaleString()}&nbsp;บาท&nbsp;(${budgetThaiText})&nbsp;ซึ่งรวมภาษีมูลค่าเพิ่มแล้ว&nbsp;นั้นธนาคารอาคารสงเคราะห์&nbsp;พิจารณาแล้ว&nbsp;ตกลงซื้อเป็นเงินทั้งสิ้น&nbsp;${budget.toLocaleString()}&nbsp;บาท&nbsp;(${budgetThaiText})&nbsp;ซึ่งรวมภาษีมูลค่าเพิ่มแล้วนั้น&nbsp;โดยท่านจะต้องติดต่อ&nbsp;ธนาคารเพื่อทำสัญญาพร้อมทั้งนำหลักฐานเอกสารประกอบการทำสัญญาและหลักประกันสัญญาร้อยละ&nbsp;5.00&nbsp;ของราคาทั้งหมดตามสัญญา&nbsp;เป็นจำนวนเงิน&nbsp;${guarantee.toLocaleString()}&nbsp;บาท&nbsp;(${guaranteeThaiText})&nbsp;(ตามเอกสาร)</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;โดยขอให้บริษัทฯ&nbsp;จัดส่งเอกสารมาที่&nbsp;ส่วนบริหารสัญญา&nbsp;ฝ่ายจัดหาและการพัสดุ&nbsp;อาคาร&nbsp;2&nbsp;ชั้น&nbsp;4&nbsp;ธนาคารอาคารสงเคราะห์&nbsp;สำนักงานใหญ่&nbsp;เลขที่&nbsp;63&nbsp;ถนนพระราม&nbsp;9&nbsp;แขวงห้วยขวาง&nbsp;เขตห้วยขวาง&nbsp;กรุงเทพมหานคร&nbsp;10310&nbsp;ภายใน&nbsp;7&nbsp;วัน&nbsp;นับตั้งแต่วันที่ได้รับหนังสือฉบับนี้&nbsp;หลังจากนั้นธนาคารจะแจ้งนัดหมายมาลงนามในสัญญาต่อไป</p></br><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ขอแสดงความนับถือ</p><p>ส่วนบริหารสัญญา&nbsp;ฝ่ายจัดหาและการพัสดุ</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ธนาคารอาคารสงเคราะห์</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;โทร.02-2022105&nbsp;,&nbsp;02-2022109</p>`;

    // Clear files and start fresh - always download latest PDFs (documents may have been edited)
    files.value = [];

    // Filter out auto-generated PDFs from saved attachments, keep only user-uploaded files
    const autoGeneratedPatterns = ['TOR.pdf', 'ราคากลาง.pdf', 'เชิญชวน'];
    const userUploadedFiles = entrepreneur.value.attachments
      ? entrepreneur.value.attachments.filter(a => !autoGeneratedPatterns.some(p => a.fileName.includes(p)))
      : [];
    files.value = [...userUploadedFiles];

    // Auto-attach approved PDFs (always download fresh) - download in parallel
    const procurementId = procurementStore.procurementDetail.id;

    if (procurementId) {
      // Prepare parallel download promises
      const downloadPromises: Promise<{ fileId: string; fileName: string } | null>[] = [];
      const downloadTypes: string[] = [];

      // Add TOR PDF download if approved
      if (procurementStore.procurementDetail.torDraft?.status === 'Approved' && procurementStore.procurementDetail.torDraft?.id) {
        downloadPromises.push(
          PP006Service.downloadTorDraftPdfAsync(
            procurementId,
            procurementStore.procurementDetail.torDraft.id
          )
        );
        downloadTypes.push('TOR');
      }

      // Add MedianPrice PDF download if approved
      if (procurementStore.procurementDetail.medianPrice?.status === 'Approved' && procurementStore.procurementDetail.medianPrice?.id) {
        downloadPromises.push(
          PP006Service.downloadMedianPricePdfAsync(
            procurementId,
            procurementStore.procurementDetail.medianPrice.id
          )
        );
        downloadTypes.push('MedianPrice');
      }

      // Add Invite PDF download if approved
      if (store.detail.status === PP006Status.Approved && store.detail.id) {
        if (!props.entrepreneurId) return;

        downloadPromises.push(
          PP006Service.downloadInvitePdfAsync(
            procurementId,
            store.detail.id,
            props.entrepreneurId,
          )
        );
        downloadTypes.push('Invite');
      }

      // Execute all downloads in parallel
      if (downloadPromises.length > 0) {
        isLoadingFiles.value = true;
        const results = await Promise.allSettled(downloadPromises);
        const failedDownloads: string[] = [];

        results.forEach((result, index) => {
          if (result.status === 'fulfilled' && result.value) {
            // Successfully downloaded and uploaded
            const attachment: OnlyFileAttachment = {
              fileId: result.value.fileId,
              fileName: result.value.fileName,
              sequence: files.value.length + 1,
            };
            files.value = [...files.value, attachment];
          } else {
            // Failed to download or upload
            failedDownloads.push(downloadTypes[index]);
            console.error(`Error auto-attaching ${downloadTypes[index]} PDF:`, result.status === 'rejected' ? result.reason : 'Download returned null');
          }
        });

        // Show warning toast if any downloads failed
        if (failedDownloads.length > 0) {
          const failedList = failedDownloads.join(', ');
          ToastHelper.warning(
            'ไม่สามารถแนบไฟล์บางรายการได้',
            `ไม่สามารถดาวน์โหลดเอกสาร ${failedList} อัตโนมัติ กรุณาแนบไฟล์ด้วยตนเอง`
          );
        }
        isLoadingFiles.value = false;
      }
    }
  } else {
    email.value = '';
    editorContent.value = '';
    files.value = [];
  }
});
</script>

<template>
  <Dialog :visible="modelValue" modal :header="'เชิญชวนผู้ประกอบการ'" :style="{ width: '100rem' }"
    @update:visible="(val) => emit('update:modelValue', val)">
    <div class="space-y-4">
      <div>
        <p class="font-bold mb-2">คู่ค้า</p>
        <p class="mb-2">{{ entrepreneur?.entrepreneurName }}</p>

        <label for="email-input" class="block mb-2">
          E-mail<span class="text-red-500">*</span>
        </label>
        <input id="email-input" v-model="email" type="email"
          class="w-full border-1 border-gray-300 rounded-md px-3 py-2" placeholder="E-mail" />
      </div>

      <div>
        <Editor v-model="editorContent" editorStyle="height: 320px" />
      </div>

      <div class="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
        <input type="file" id="fileUpload" class="hidden" multiple @change="onFileSelect" />
        <label for="fileUpload" class="cursor-pointer">
          <div class="flex flex-col items-center gap-2">
            <span class="material-symbols-outlined text-gray-400 text-5xl">cloud_upload</span>
            <p class="text-gray-500">คลิกที่นี่เพื่อเลือกไฟล์ของคุณ</p>
            <p class="text-gray-400 text-sm">ขนาด : JPG, PNG, XLS ,XLSX (ขนาด 15 MB)</p>
          </div>
        </label>
      </div>

      <div v-if="isLoadingFiles"
        class="flex items-center justify-center gap-2 p-4 border-1 border-gray-300 rounded-lg bg-gray-50">
        <i class="pi pi-spin pi-spinner text-xl text-primary"></i>
        <span class="text-gray-600">กำลังดาวน์โหลดเอกสารแนบ...</span>
      </div>

      <div v-if="files.length > 0" class="space-y-2">
        <div v-for="(file, index) in files" :key="index"
          class="flex items-center justify-between border-1 border-gray-300 rounded-lg p-2">
          <div class="flex items-center gap-2">
            <span class="material-symbols-outlined">description</span>
            <span>{{ file.fileName }}</span>
          </div>
          <div class="flex items-center gap-2">
            <Button icon="pi pi-trash" severity="danger" text @click="() => onRemoveFile(index)" />
            <span class="material-symbols-outlined cursor-pointer">more_vert</span>
          </div>
        </div>
      </div>
    </div>

    <template #footer>
      <div class="flex justify-end gap-2">
        <Button label="ยกเลิก" severity="secondary" variant="outlined" @click="onClose" />
        <Button label="ยืนยันส่งเมล" icon="pi pi-send" severity="success" @click="onSendEmail"
          :disabled="!email || isLoadingFiles" />
      </div>
    </template>
  </Dialog>
</template>
