<script setup lang="ts">
import ToastHelper from '@/helpers/toast';
import type { OnlyFileAttachment } from '@/models/shared/uploadFile';
import ST003Service from '@/services/file';
import { usePPDetailStore } from '@/stores/PP/ppStore';
import { PP009Status } from '@/views/PP/enums/pp009';
import PP009Service from '@/views/PP/services/PP009/PP009Service';
import { usePP009DetailStore } from '@/views/PP/stores/PP009/PP009Store';
import { HttpStatusCode } from 'axios';
import { Button, Dialog } from 'primevue';
import Editor from 'primevue/editor';
import { computed, ref, watch } from 'vue';

type Props = {
  modelValue: boolean;
  vendorId?: string;
};

const props = defineProps<Props>();

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
}>();

const procurementStore = usePPDetailStore();
const store = usePP009DetailStore();
const email = ref('');
const files = ref<OnlyFileAttachment[]>([]);
const editorContent = ref('');
const isLoadingFiles = ref(false);

const vendor = computed(() => {
  if (!props.vendorId) return null;
  return store.body.vendors.find(v => v.id === props.vendorId);
});

const onClose = (): void => {
  email.value = '';
  editorContent.value = '';
  files.value = [];
  emit('update:modelValue', false);
};

const onSendEmail = async (): Promise<void> => {
  if (!props.vendorId) return;

  await store.fn.onSendEmailInviteAsync(props.vendorId, email.value, editorContent.value, files.value);
  onClose();
};

const onFileSelect = async (event: Event): Promise<void> => {
  const target = event.target as HTMLInputElement;
  if (!target.files) return;

  const fileList = Array.from(target.files);

  for (const file of fileList) {
    const { data, status } = await ST003Service.uploadFile(file);

    if (status === HttpStatusCode.Ok) {
      const uploadedFile: OnlyFileAttachment = {
        fileId: data.id,
        fileName: file.name,
        sequence: files.value.length + 1,
      };

      files.value = [...files.value, uploadedFile];
    }
  }

  target.value = '';
};

const onRemoveFile = (index: number): void => {
  files.value.splice(index, 1);
};

watch(() => props.modelValue, async (newValue) => {
  if (newValue && vendor.value) {
    email.value = vendor.value.emailSend || vendor.value.email || '';

    editorContent.value = vendor.value.emailTemplate || `<p>เรียน&nbsp;&nbsp;${vendor.value.entrepreneur?.establishmentName || 'establishmentName'}</p><p></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ด้วย&nbsp;ธนาคารอาคารสงเคราะห์&nbsp;มีความประสงค์จะขอเรียนเชิญท่าน&nbsp;ให้มาจัดทำสัญญา&nbsp;ดังรายละเอียดตามเอกสารแบบฉบับนี้</p><p></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ทั้งนี้&nbsp;ขอให้ท่านจัดส่งเอกสารมาที่&nbsp;ส่วนบริหารสัญญา&nbsp;ฝ่ายจัดหาและการพัสดุ&nbsp;อาคาร&nbsp;2&nbsp;ชั้น&nbsp;4&nbsp;ธนาคารอาคารสงเคราะห์&nbsp;สำนักงานใหญ่&nbsp;เลขที่&nbsp;63&nbsp;ถนนพระราม&nbsp;9&nbsp;แขวงห้วยขวาง&nbsp;กรุงเทพมหานคร&nbsp;10310&nbsp;ภายใน&nbsp;7&nbsp;วัน&nbsp;นับตั้งแต่วันที่ได้รับหนังสือฉบับนี้&nbsp;หลังจากนั้นธนาคารจะแจ้งนัดหมายมาลงนามสัญญาต่อไป</p>`;
    // Clear files and filter out auto-generated PDFs from saved attachments
    files.value = [];
    const autoGeneratedPatterns = ['หนังสือเชิญชวนทำสัญญา.pdf'];
    const userUploadedFiles = vendor.value.emailAttachments
      ? vendor.value.emailAttachments.filter(a =>
        !autoGeneratedPatterns.some(p => a.fileName.includes(p))
      )
      : [];
    files.value = [...userUploadedFiles];

    // Auto-attach contract invitation PDF if status is Approved
    const procurementId = procurementStore.procurementDetail.id;
    const contractInvitationId = store.body.id;
    const vendorId = vendor.value.id;

    if (store.body.status === PP009Status.Approved && procurementId && contractInvitationId && vendorId) {
      isLoadingFiles.value = true;

      const result = await PP009Service.downloadContractInvitationPdfAsync(
        procurementId,
        contractInvitationId,
        vendorId
      );

      if (result) {
        const attachment: OnlyFileAttachment = {
          fileId: result.fileId,
          fileName: result.fileName,
          sequence: files.value.length + 1,
        };
        files.value = [...files.value, attachment];
      } else {
        ToastHelper.warning(
          'ไม่สามารถแนบไฟล์ได้',
          'ไม่สามารถดาวน์โหลดเอกสารหนังสือเชิญชวนทำสัญญาอัตโนมัติ กรุณาแนบไฟล์ด้วยตนเอง'
        );
      }

      isLoadingFiles.value = false;
    }
  } else {
    email.value = '';
    editorContent.value = '';
    files.value = [];
  }
});
</script>

<template>
  <Dialog :visible="modelValue" modal :header="'เชิญชวนทำสัญญา'" :style="{ width: '100rem' }"
    @update:visible="(val) => emit('update:modelValue', val)">
    <div class="space-y-4">
      <div>
        <p class="font-bold mb-2">คู่ค้า</p>
        <p class="mb-2">{{ vendor?.vendorName }}</p>

        <label for="email-input" class="block mb-2">
          E-mail<span class="text-red-500">*</span>
        </label>
        <input id="email-input" v-model="email" type="email" class="w-full border-1 border-gray-300 rounded-md px-3 py-2"
          placeholder="E-mail" />
      </div>

      <div>
        <Editor v-model="editorContent" editorStyle="height: 320px" />
      </div>

      <div class="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center">
        <input type="file" id="fileUpload" class="hidden" multiple @change="onFileSelect" />
        <label for="fileUpload" class="cursor-pointer">
          <div class="flex flex-col items-center gap-2">
            <span class="material-symbols-outlined text-gray-400 text-5xl">cloud_upload</span>
            <p class="text-gray-500">คลิกที่นี่เพื่อเลือกไฟล์ของคุณ</p>
            <p class="text-gray-400 text-sm">ขนาด : JPG, PNG, XLS ,XLSX (ขนาด 15 MB)</p>
          </div>
        </label>
      </div>

      <div v-if="isLoadingFiles"
        class="flex items-center justify-center gap-2 p-4 border-1 border-gray-300 rounded-lg bg-gray-50">
        <i class="pi pi-spin pi-spinner text-xl text-primary"></i>
        <span class="text-gray-600">กำลังดาวน์โหลดเอกสารแนบ...</span>
      </div>

      <div v-if="files.length > 0" class="space-y-2">
        <div v-for="(file, index) in files" :key="index"
          class="flex items-center justify-between border-1 border-gray-300 rounded-lg p-2">
          <div class="flex items-center gap-2">
            <span class="material-symbols-outlined">description</span>
            <span>{{ file.fileName }}</span>
          </div>
          <div class="flex items-center gap-2">
            <Button icon="pi pi-trash" severity="danger" text @click="() => onRemoveFile(index)" />
            <span class="material-symbols-outlined cursor-pointer">more_vert</span>
          </div>
        </div>
      </div>
    </div>

    <template #footer>
      <div class="flex justify-end gap-2">
        <Button label="ยกเลิก" severity="secondary" variant="outlined" @click="onClose" />
        <Button label="ยืนยันส่งเมล" icon="pi pi-send" severity="success" @click="onSendEmail"
          :disabled="!email || isLoadingFiles" />
      </div>
    </template>
  </Dialog>
</template>
